### ISSUE TITLE
Cythonization of run.py fails due to bindir name

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#1095]
```
./configure --compiler=g++ --mode=debug --ccache
```

This creates the following bindir:
```
bin -> .bin/g++-debug-Oauto-sanitize-none
```

When I `make cythonize`, Cython complains to compile the file:
```
jj@jjpad ~/devel/openage % make cythonize VERBOSE=1
make  -C bin cythonize
make[1]: Entering directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
/usr/bin/cmake -S/home/jj/devel/openage -B/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 cythonize
make[2]: Entering directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
/usr/bin/cmake -S/home/jj/devel/openage -B/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none/CMakeFiles 0
make -f CMakeFiles/Makefile2 CMakeFiles/cythonize.dir/all
make[3]: Entering directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
make -f CMakeFiles/cythonize.dir/build.make CMakeFiles/cythonize.dir/depend
make[4]: Entering directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
cd /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jj/devel/openage /home/jj/devel/openage /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none/CMakeFiles/cythonize.dir/DependInfo.cmake --color=
make[4]: Leaving directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
make -f CMakeFiles/cythonize.dir/build.make CMakeFiles/cythonize.dir/build
make[4]: Entering directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
cythonize.py: compiling .pyx files to .cpp
cd /home/jj/devel/openage && /usr/lib/python-exec/python3.6/python3 -m buildsystem.cythonize /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none/py/cython_modules /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none/py/cython_modules_embed /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none/py/pxd_list --build-dir /home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none
[1/1] Cythonizing run.py

Error compiling Cython file:
------------------------------------------------------------
...
#!/usr/bin/env python3
^
------------------------------------------------------------

run.py:1:0: 'g++-debug-Oauto-sanitize-none.run' is not a valid module name
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jj/devel/openage/buildsystem/cythonize.py", line 190, in <module>
    main()
  File "/home/jj/devel/openage/buildsystem/cythonize.py", line 167, in main
    cythonize_wrapper(embedded_modules, **cythonize_args)
  File "/home/jj/devel/openage/buildsystem/cythonize.py", line 94, in cythonize_wrapper
    cythonize(bin_modules, **kwargs)
  File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/usr/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: run.py
make[4]: *** [CMakeFiles/cythonize.dir/build.make:93: py/cythonize_timefile] Error 1
make[4]: Leaving directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
make[3]: *** [CMakeFiles/Makefile2:1127: CMakeFiles/cythonize.dir/all] Error 2
make[3]: Leaving directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
make[2]: *** [CMakeFiles/Makefile2:1138: CMakeFiles/cythonize.dir/rule] Error 2
make[2]: Leaving directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
make[1]: *** [Makefile:626: cythonize] Error 2
make[1]: Leaving directory '/home/jj/devel/openage/.bin/g++-debug-Oauto-sanitize-none'
make: *** [Makefile:61: cythonize] Error 2
```

The cythonization is registered in the root `CMakeLists.txt`, and this is likely the source for the module name. We somehow have to sanitize it or strip it out completely.
```
add_cython_modules(EMBED NOINSTALL ${CMAKE_CURRENT_BINARY_DIR}/run.py)
```

**Comment by TheJJ** [comment]
Oh well. Fixed by removing `bin/__init__.py` and `bin/__init__.pxd`... Cython thought the file was within a Python package because the `init` py was still there and prepended the path name.
