### ISSUE TITLE
AoE2:DE Support

### ISSUE THREAD

**Issue by sandsmark** [SFTtech/openage#1192]
Might as well start an issue for this (I hope that's okay). 

Just downloaded it and started looking at the data files, and seems they have changed the graphics format again, now it is .smx files. Haven't gotten very far yet, just diffed a couple with dhex, and it seems like the header is now `53 4d 50 58 02 00`, so 'SMPX' followed by 0x2 0x0 (that seems to be constant). Then there's two int32s, it seems, that varies in different graphics for the same unit, so I assume it is frame numbers.

I'm not sure if they did this with AoE:DE, but now they actually have a `Tools_Build` folder with various tools for modding, including a tool (`DEAssetTool.exe`) for converting SLPs or PSDs to SM(P)X files, which will probably help a lot. A fun fact is that they also include AGE/genieutils, which I guess indicates that the .dat formats haven't changed (I don't see the source anywhere for it, so I assume they haven't modified it, it being GPL and all). :-)

They also seem to do the terrain blending and hill stuff in shaders (I think they did the same in AoE1:DE), and also the conversion from SMP to RGB.

But now it's getting late, just wanted to get this down somewhere.

**Comment by sandsmark** [comment]
As for the other types of assets, they now use wwise for audio. And for some reason they seem to be including some ffmpeg stuff, but they also include lame so might just be for streaming support, I think they integrate with Mixer directly? it doesn't run in wine yet, so haven't actually run it.

**Comment by heinezen** [comment]
SMX conversion support will be added on Sunday, probably :) We've already figured out how it works, so documentation will come along with it to extend the already existing SMP file specs.
The .dat file has one new entry (blood sprite ID, `int16`, comes after dead unit ID) that is xclusively used by the Konnik.  

Fun fact: Microsoft violates the GPL with DE2 because they do not include a GPL license file for genieutils and AGE3 in the Tools Builds folder :laughing:

**Comment by simonsan** [comment]
@sandsmark Here are instructions how to get AoE2DE running on Wine: https://www.reddit.com/r/aoe2/comments/dwuplr/how_to_run_age_of_empires_2_definitive_edition_on/

**Comment by sandsmark** [comment]
> SMX conversion support will be added on Sunday, probably :) We've already figured out how it works, so documentation will come along with it to extend the already existing SMP file specs.
> The .dat file has one new entry (blood sprite ID, `int16`, comes after dead unit ID) that is xclusively used by the Konnik.

Goddamn you're fast. :-)

I think reversing (technically) all the data formats in less than 10 days must be some kind of record. Though I guess it's kind of cheating when they share a lot of the code with something people have been picking apart for 20+ years. :p

> Fun fact: Microsoft right now violates the GPL with DE2 because they do not include a GPL license file for genieutils and AGE3 in the Tools Builds folder

Hah, true. I was thinking about contacting them because I have [a fork of AGE](https://github.com/sandsmark/AGE) with a couple of new features (among other things).

I think they just put in whatever is in the zip file Tapsa publishes on aokheaven though, so it's an easy mistake to make. But then again I would assume their lawyers would be pretty wary of anything GPL (most of our lawyers are, except for the one who's an openbsd user).

**Comment by sandsmark** [comment]
> @sandsmark Here are instructions how to get AoE2DE running on Wine: https://www.reddit.com/r/aoe2/comments/dwuplr/how_to_run_age_of_empires_2_definitive_edition_on/

Thanks! The timing of that post is a bit creepy though, that was almost exactly when I opened the exe in ghidra to debug it. :-P

**Comment by sandsmark** [comment]
Just manually tried to parse the wav header (i. e. open one in dhex) in the wwise .wem files, and it seems to be AAC compressed. In addition to being annoying to decode even with another lib dependency, it seems like it uses channel coupling which faad2 doesn't support.

Reading [this](https://docs.microsoft.com/en-us/windows/win32/medfound/aac-decoder) doc, though, it seems like Microsoft's decoder just skips frames with "channel coupling elements" which I take is what faad2 means. So faad2 refuses to continue, but just making it skip the frames with it should probably be OK.

**Comment by brisvag** [comment]
> edit; if you've tested it with proton, putting a link here would probably be nice; https://www.protondb.com/app/1017900 (I think that's where most people find information about stuff like that)

Yesterday I sent a report with a working solution (taken from some guy at the issue tracker relative to aoe2de [here](https://github.com/ValveSoftware/Proton/issues/3189#issuecomment-554796843)). The game works just fine :)

**Comment by heinezen** [comment]
#1193 for SMX is now ready :)

**Comment by TheJJ** [comment]
smx support has landed!

**Comment by sandsmark** [comment]
What asset files are missing now? Just the sounds? (Wondering if I should rename this.)

**Comment by heinezen** [comment]
@sandsmark I think it would be good to have a checklist in your top post. The new formats are

* Wwise audio formats for sounds
* SMX/SMP for sprites (already supported by us, except for the damage mask)
* DDS for terrain files
* Particle effects (JSON config files)
* A bunch of blend masks are now configured by JSON files too

And maybe more. I didn't check every folder yet.

**Comment by sandsmark** [comment]
> DDS for terrain files

**Comment by heinezen** [comment]
> groan... I looked into those for the special editions of monkey island, not a fun format.

RenderDoc has a parser for the format:

https://github.com/baldurk/renderdoc/blob/6d1d30249136e13f742f03c32ef18e09647be116/renderdoc/common/dds_readwrite.cpp

Can't recommend this program enough for people interested in rendering.

**Comment by sandsmark** [comment]
Sweet, thanks! That's the cleanest code I've seen for parsing DDS, maybe I can pick up the monkey island stuff as well.


Regarding the sounds, forgot to write it here; the files ww2ogg generates aren't playable, but vgmstream manages to convert just fine as wwise vorbis files. And vgmstream's wwise vorbis support is from ww2ogg, so probably just some fix there that could be backported.

I was originally planning to hack in support for the "broken" vorbis packets into stb_vorbis, but for openage it probably makes more sense to just fix the vorbis streams and store it as normal .oggs? Or do you want to convert everything to opus? Assuming you want to do as much of the asset conversion in Python I think just rewriting the wwise files to normal ogg files is probably easier (shouldn't be much Python code to recreate the broken/"replaced" packets).

**Comment by sandsmark** [comment]
FWIW; to look at the shaders you can use vkd3d-compiler to convert it to spirv, and then spirv-cross to convert it to glsl (or whatever you want). Seems to work fairly okay (though there seems to be some unrolling in the ConvertSMPToRGB shaders that's annoying to read).

**Comment by TheJJ** [comment]
Currently the audio system only has opus playback support, and I'd prefer to keep it that way for now (we only link against `opusfile`). If we want to support multiple codecs and whatever formats (which we should, once e.g. users want to add taunts :grin: ), we have to consider how we implement that properly (and with cross plattform support). `opus` uses `ogg` as container.

**Comment by sandsmark** [comment]
yeah, I understand not wanting to link against multiple libraries, is there a huge difference in quality between opus and vorbis for the AoE sounds? Otherwise just using vorbis for everything might be easier.

and ref container; wwise is just a semi-custom wav/riff container + various codecs, but for DE they use vorbis. the problem is just that they mangle the vorbis stream a bit in their container, so to convert to "normal" .ogg you just need to load the .wwise (the container is more or less just standard RIFF but with an extended header afaik, recreate the missing vorbis header and slightly unmangle packets, and write it out to an .ogg file like any normal vorbis stream. tada, normal ogg vorbis.

**Comment by simonsan** [comment]
>  is there a huge difference in quality between opus and vorbis for the AoE sounds
Yes, opus is the superior format for audio and speech. To use **ogg vorbis** seems like a step back in this regards.
https://opus-codec.org/comparison/

**Comment by TheJJ** [comment]
I guess we won't be able to hear the difference, especially since we convert it from $source to opus, and the quality of source can't be magically better after conversion. As vorbis is also by xiph and our audio system is of course prepared to handle multiple codecs, we could add it quite easily. Then we can perform your conversion from above.
Alternatively, we could just read the file (with whatever codec necessary) and still convert it to opus, just because we can :) We selected opus as target codec because we want to be hipster and the source files were `wav` only :stuck_out_tongue:.

**Comment by heinezen** [comment]
The only other codec we maybe should prioritize is FLAC I think because it's losless like .wav. Other formats are still useful if someoe wants to import their own music playlist or mod sound files with other codecs in, but .opus and FLAC should cover 99% of use cases.

**Comment by simonsan** [comment]
> the quality of source can't be magically better after conversion

Just some thoughts: This will not happen wit a simple conversion, but maybe with something like an [music enhancement algorithm](https://arxiv.org/pdf/1812.08466v1.pdf) (Fréchet Audio Distance: A Metric for Evaluating Music Enhancement Algorithms) that we might be able to use in the future. Would be also quite interesting to use software to "automagically" reverse engineer the music and rearrange it to our liking but keeping some stuff (as much as we are allowed to from licensing reasons, see Kraftwerk vs. Moses P) as in the original.

**Comment by simonsan** [comment]
![2020-03-31 15_09_34-Window-Screenshot](https://user-images.githubusercontent.com/14062932/78182202-0655e480-7466-11ea-9240-8f1d868ffb0e.png)

AoE2DE supports Opus now as well, does it change anything for the `Wwise audio formats for sounds` spec in here?

**Comment by sandsmark** [comment]
> AoE2DE supports Opus now as well

I saw they used ffmpeg, but I assumed that was just for the mixer integration, but maybe they use it for more.

> does it change anything for the Wwise audio formats for sounds spec in here

Their official assets still are in wwise's format, so I don't think so (unless they change to opus in a future release).

**Comment by duanqn** [comment]
I have AOE2:DE installed via Microsoft Store and it seems the files are very well protected. I can see the files but I have no ways to read/write them.
Has anyone seen this before? Or are you all looking at the Steam version?

**Comment by heinezen** [comment]
@duanqn Apps from the MS store can be protected by UWP. You need to dump the data first, before writing/reading them with other projects. [UWPDumper](https://github.com/Wunkolo/UWPDumper) should do the trick.

**Comment by duanqn** [comment]
@heinezen Thank you. That tool looks really useful but AoE2:DE is nearly 20GB.

**Comment by sandsmark** [comment]
> Apps from the MS store can be protected by UWP. You need to dump the data first, before writing/reading them with other projects. UWPDumper should do the trick.

If someone feels up to it I guess uwpdumper compatibility could be added to the asset converter (not very useful until aoe2:de assets are supported though).

Seems fairly straightforward (famous last words), once you're in the right part of the uwpdumper code you seem to have more or less normal access to the files:
https://github.com/Wunkolo/UWPDumper/blob/master/UWPDumper/main.cpp#L91

(for those that don't know c++, that code seems to just list a directory and copy out all the files there normally, like any other program.)

**Comment by heinezen** [comment]
It would probably make sense to mount the files instead of dumping them, so that we don't need so much disk space. That would require more work though (we would need a Cython/Python interface).

**Comment by TheJJ** [comment]
That would be a new backend to the `fslike` subsystem :)  (We originally started this to transparently mount the install CD)

**Comment by TheJJ** [comment]
Here ya go: #1247. Shouldn't be highly priorized though, it's just an extension for another "source" of data, the hard work is the DE-converter itself.

**Comment by leopeng1995** [comment]
I purchased `Age of Empires II: Definitive Edition` on Steam. After installing it on Windows, I compressed the `<Steam Installed Directory>\steamapps\common\AoE2DE` folder into a zip file and transferred it to Ubuntu. When I tried to run the resource conversion using `./run main`, I got an error:

```
$ ./run main
INFO [py] launching openage v0.6.0-96-g6d9d8d75
INFO [py] compiled by GNU 13.3.0
INFO [py] running in DEVMODE
INFO [py] openage nyan API modpack is up to date
  Do you want to convert assets? [Y/n]
> Y

Please select an Age of Empires installation directory.
Insert the index of one of the proposals, or any path:
(0) /tmp/tmps0dysmiq
> /home/leo/Games/AoE2DE
converting from '/home/leo/Games/AoE2DE'
INFO [py] Looking for compatible games to convert...
INFO [py] Compatible game edition detected:
INFO [py]  * Age of Empires 2: Definitive Edition
Traceback (most recent call last):
  File "run.py", line 20, in init run
    main()
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 168, in main
    return args.entrypoint(args, cli.error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/main/main.py", line 97, in main
    convert_assets(asset_path, args)
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/main.py", line 98, in convert_assets
    data_dir = mount_asset_dirs(srcdir, args.game_version)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/service/init/mount_asset_dirs.py", line 52, in mount_asset_dirs
    raise FileNotFoundError(f"Media at path {path_to_media} could not be found")
FileNotFoundError: Media at path [Directory(/home/leo/Games/AoE2DE)]:wwise could not be found
```

I noticed there's an `Age of Empires II: Definitive Edition Soundtrack` on Steam. Do I need to purchase this separately?

**Comment by heinezen** [comment]
@leopeng1995 I just tried out the latest version from Steam and the folder that's missing in your error definitely still exists. I don't know how you transferred the file, but maybe that was the problem. You can also install Steam on Ubuntu and download it directly if that helps.

While running the converter on the latest version, I found another bug in the converter code that currently leads to crashes, so I'm going to try to fix that. If you don't want to wait for that, there is the AoC trial version which you can use. It is free and the converter can automatically download it if you don't pass it an folder with another AoE installation.

**Comment by leopeng1995** [comment]
![Image](https://github.com/user-attachments/assets/79e387e0-ce3a-45a6-b6d8-5e68aca9237f)

This is my folder list in <Steam Installed Directory>\steamapps\common\AoE2DE\resources\_common on Windows, but I don't see the "sounds" and "audios" folders. This might not be related to the packaging and transmission method, as the directories downloaded on Windows don't have them either. I've already used Steam's "Verify Integrity of Game Files" feature to check. I'll try downloading it using Steam on Ubuntu. It's also possible that the game package you purchased includes music files by default. Thank you for your reply. @heinezen

**Comment by heinezen** [comment]
@leopeng1995 Ah did you only compress the `AoE2DE\resources\_common` subfolder? Because the error you got is for a failed mount of the `AoE2DE\wwise` subfolder which is located inside the main installation directory on Steam (i.e. `AoE2DE`). For reference, this is how the `AoE2DE` directory looks for me. You should pass the path to this directory to the openage converter:

![Image](https://github.com/user-attachments/assets/5b276e37-4636-44d4-b929-a901cfe2b246)

**Comment by leopeng1995** [comment]
![Image](https://github.com/user-attachments/assets/00eeb4b0-c44a-4401-b1e3-45c3aa95c008)

```
eo@leo-VMware-Virtual-Platform:~/workspaces/openage/bin$ ./run main
INFO [py] launching openage v0.6.0-96-g6d9d8d75
INFO [py] compiled by GNU 13.3.0
INFO [py] running in DEVMODE
INFO [py] openage nyan API modpack is up to date
  Do you want to convert assets? [Y/n]
> Y

openage requires a local game installation for conversion
but no local installation could be found automatically.
  Do you want to download the AoC trial version? [Y/n]
> n
Could not find any installation directory automatically.
Please enter an AOE2 install path manually.
> /home/leo/Games/AoE2DE
converting from '/home/leo/Games/AoE2DE'
INFO [py] Looking for compatible games to convert...
INFO [py] Compatible game edition detected:
INFO [py]  * Age of Empires 2: Definitive Edition
INFO [py] converting metadata
Traceback (most recent call last):
  File "run.py", line 20, in init run
    main()
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 168, in main
    return args.entrypoint(args, cli.error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/main/main.py", line 97, in main
    convert_assets(asset_path, args)
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/main.py", line 121, in convert_assets
    convert(args)
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/tool/driver.py", line 35, in convert
    convert_metadata(args)
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/tool/driver.py", line 72, in convert_metadata
    gamespec = get_gamespec(args.srcdir, args.game_version, not args.flag("no_pickle_cache"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/service/read/gamedata.py", line 47, in get_gamespec
    gamespec = load_gamespec(empiresdat_file,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/service/read/gamedata.py", line 102, in load_gamespec
    _, gamespec = wrapper.read(file_data, 0, game_version, dynamic_load=dynamic_load)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 133, in read
    offset, gen_members = self._read_multisubtye(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 309, in _read_multisubtye
    offset, gen_members = new_data.read(raw, offset, game_version, new_data_class)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 133, in read
    offset, gen_members = self._read_multisubtye(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 309, in _read_multisubtye
    offset, gen_members = new_data.read(raw, offset, game_version, new_data_class)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 133, in read
    offset, gen_members = self._read_multisubtye(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 309, in _read_multisubtye
    offset, gen_members = new_data.read(raw, offset, game_version, new_data_class)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 140, in read
    offset, gen_members, stop_reading_members = self._read_primitive(
                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 523, in _read_primitive
    lookup_result = var_type.entry_hook(result)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/workspaces/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/read_members.py", line 314, in entry_hook
    raise KeyError("failed to find %s%s in lookup dict %s!" %
KeyError: 'failed to find 202 = 0xca in lookup dict effect_apply_type!'
```

@heinezen  I packed and transferred the entire folder `<Steam Installed Directory>\steamapps\common\AoE2DE` to Ubuntu's corresponding `/home/leo/Games/AoE2DE`. I also noticed the `wwise` folder, but after running the `./run main` command, I encountered a new error: `KeyError: 'failed to find 202 = 0xca in lookup dict effect_apply_type!'`. I haven't made any changes to the code.

**Comment by leopeng1995** [comment]
https://github.com/SFTtech/openage/issues/1701 Perhaps this issue is related; it's possible that AoE2DE has updated its game resources?

**Comment by 0xrushi** [comment]
+1 not sure if internally uses wine, but my AOE2 definitive edition works fine when I play it on steam.
But I'm getting the below error when I try to `./run main`

```
doraemon@doraemon-arch bin]$ ./run main
INFO [py] launching openage v0.6.0-197-g865bd548
INFO [py] compiled by GNU 13.3.0
INFO [py] running in DEVMODE
INFO [py] openage nyan API modpack is up to date
  Do you want to convert assets? [Y/n]
> Y

Please select an Age of Empires installation directory.
Insert the index of one of the proposals, or any path:
(0) ~/.steam/steam/steamapps/common/AoE2DE
> 0
converting from '/home/doraemon/.local/share/Steam/steamapps/common/AoE2DE'
INFO [py] Looking for compatible games to convert...
INFO [py] Compatible game edition detected:
INFO [py]  * Age of Empires 2: Definitive Edition
INFO [py] converting metadata
Traceback (most recent call last):
  File "run.py", line 20, in init run
    main()
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 168, in main
    return args.entrypoint(args, cli.error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/main/main.py", line 97, in main
    convert_assets(asset_path, args)
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/main.py", line 121, in convert_assets
    convert(args)
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/tool/driver.py", line 35, in convert
    convert_metadata(args)
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/tool/driver.py", line 72, in convert_metadata
    gamespec = get_gamespec(args.srcdir, args.game_version, not args.flag("no_pickle_cache"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/service/read/gamedata.py", line 47, in get_gamespec
    gamespec = load_gamespec(empiresdat_file,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/service/read/gamedata.py", line 102, in load_gamespec
    _, gamespec = wrapper.read(file_data, 0, game_version, dynamic_load=dynamic_load)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 133, in read
    offset, gen_members = self._read_multisubtye(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 309, in _read_multisubtye
    offset, gen_members = new_data.read(raw, offset, game_version, new_data_class)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 133, in read
    offset, gen_members = self._read_multisubtye(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 309, in _read_multisubtye
    offset, gen_members = new_data.read(raw, offset, game_version, new_data_class)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 133, in read
    offset, gen_members = self._read_multisubtye(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 309, in _read_multisubtye
    offset, gen_members = new_data.read(raw, offset, game_version, new_data_class)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 140, in read
    offset, gen_members, stop_reading_members = self._read_primitive(
                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/genie_structure.py", line 523, in _read_primitive
    lookup_result = var_type.entry_hook(result)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/doraemon/Documents/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/value_object/read/read_members.py", line 314, in entry_hook
    raise KeyError("failed to find %s%s in lookup dict %s!" %
KeyError: 'failed to find 202 = 0xca in lookup dict effect_apply_type!'
[doraemon@doraemon-arch bin]$ 


```
