### ISSUE TITLE
util::tests::enum_ fails on Windows builds

### ISSUE THREAD

**Issue by simonsan** [SFTtech/openage#1243]
This is from the Win10 package tests:
```
[19/31] cpp util::tests::enum_
Test failed
Unexpected exception
Traceback (most recent call last):
  File "C:\Users\username\Desktop\upscaling-project\Pipeline\1 Convert\openage-v0.4.0-60-g323e7c1a-amd64-portable_NIGHTLY\python\openage\testing\main.py", line 130, in main
    testfun()
  File "C:\Users\username\Desktop\upscaling-project\Pipeline\1 Convert\openage-v0.4.0-60-g323e7c1a-amd64-portable_NIGHTLY\python\openage\testing\list_processor.py", line 114, in runner
    run_cpp_method(name)
  File "openage\testing\cpp_testing.pyx", line 12, in openage.testing.cpp_testing.run_cpp_method
RuntimeError: unexpected value: struct openage::util::tests::testenum_value::foo
```

Building with Visual Studio 2019 in `Debug` mode I've got these related errors that could help us resolve the issue, probably?

```
2020-04-27T23:37:18.1970377Z misc_cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl openage::util::EnumValue<struct openage::util::tests::testenum_value,int>::operator<=(struct openage::util::tests::testenum_value const &)const "(__imp_??N?$EnumValue@Utestenum_value@tests@util@openage@@H@util@openage@@QEBA_NAEBUtestenum_value@tests@12@@Z) referenced in function "struct _object * __cdecl __pyx_pf_7openage_7testing_8misc_cpp_enum(struct _object *)" (?__pyx_pf_7openage_7testing_8misc_cpp_enum@@YAPEAU_object@@PEAU1@@Z) [D:\a\openage\build-openage\openage\testing\openage_testing_misc_cpp.vcxproj]

2020-04-27T23:37:18.1972360Z misc_cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl openage::util::EnumValue<struct openage::util::tests::testenum_value,int>::operator<(struct openage::util::tests::testenum_value const &)const " (__imp_??M?$EnumValue@Utestenum_value@tests@util@openage@@H@util@openage@@QEBA_NAEBUtestenum_value@tests@12@@Z) referenced in function "struct _object * __cdecl __pyx_pf_7openage_7testing_8misc_cpp_enum(struct _object *)" (?__pyx_pf_7openage_7testing_8misc_cpp_enum@@YAPEAU_object@@PEAU1@@Z) [D:\a\openage\build-openage\openage\testing\openage_testing_misc_cpp.vcxproj]

2020-04-27T23:37:18.1973152Z misc_cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl openage::util::EnumValue<struct openage::util::tests::testenum_value,int>::operator>=(struct openage::util::tests::testenum_value const &)const " (__imp_??P?$EnumValue@Utestenum_value@tests@util@openage@@H@util@openage@@QEBA_NAEBUtestenum_value@tests@12@@Z) referenced in function "struct _object * __cdecl __pyx_pf_7openage_7testing_8misc_cpp_enum(struct _object *)" (?__pyx_pf_7openage_7testing_8misc_cpp_enum@@YAPEAU_object@@PEAU1@@Z) [D:\a\openage\build-openage\openage\testing\openage_testing_misc_cpp.vcxproj]

2020-04-27T23:37:18.1998390Z misc_cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl openage::util::EnumValue<struct openage::util::tests::testenum_value,int>::operator>(struct openage::util::tests::testenum_value const &)const " (__imp_??O?$EnumValue@Utestenum_value@tests@util@openage@@H@util@openage@@QEBA_NAEBUtestenum_value@tests@12@@Z) referenced in function "struct _object * __cdecl __pyx_pf_7openage_7testing_8misc_cpp_enum(struct _object *)" (?__pyx_pf_7openage_7testing_8misc_cpp_enum@@YAPEAU_object@@PEAU1@@Z) [D:\a\openage\build-openage\openage\testing\openage_testing_misc_cpp.vcxproj]

2020-04-27T23:37:18.1999661Z misc_cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct openage::util::tests::testenum_value const & __cdecl openage::util::Enum<struct openage::util::tests::testenum_value>::get(void)const " (__imp_?get@?$Enum@Utestenum_value@tests@util@openage@@@util@openage@@QEBAAEBUtestenum_value@tests@23@XZ) referenced in function "struct _object * __cdecl __pyx_pf_7openage_7testing_8misc_cpp_enum(struct _object *)" (?__pyx_pf_7openage_7testing_8misc_cpp_enum@@YAPEAU_object@@PEAU1@@Z) [D:\a\openage\build-openage\openage\testing\openage_testing_misc_cpp.vcxproj]
```

**Comment by simonsan** [comment]
![scan-build](https://user-images.githubusercontent.com/14062932/80662302-3b6b4c00-8a91-11ea-92e3-ee07fed8e9b0.png)

**Comment by heinezen** [comment]
Since Windows CI builds run fine, I guess this resolved itself.
