### ISSUE TITLE
Crash when using "4321" as generation seed.

### ISSUE THREAD

**Issue by SeanRamey** [SFTtech/openage#1279]
I've built openage on my archlinux system. Everything builds fine, but the default seed is 4321, and it crashes the game upon "generate_game".
The output is as follows:
```
[  0%] Automatic MOC for target libopenage
bin/run game
INFO [py] launching openage v0.4.0-160-g3b2d966e
INFO [py] compiled by GNU 10.1.0
INFO [py] running in DEVMODE
INFO launching engine with Path(Union(Directory(/home/sean/Coding/openage/cfg).root @ (b'cfg',), Directory(/home/sean/Coding/openage/assets).root @ (b'assets',)):) and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=2, samples=4096]
INFO Initialized SDL video subsystems.
INFO Compiled with Qt 5.15.0 and run with Qt 5.15.0
INFO loading configuration files...
INFO [py] loading config file [Union(Directory(/home/sean/Coding/openage/cfg).root @ (b'cfg',), Directory(/home/sean/Coding/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
INFO Loading time [engine]: 0.209 s
INFO Loading time   [game]: 0.227 s
INFO [T1] Loading game specification files...
INFO [T1] Loaded multi-csv file: 45484 sub-files
INFO [T1] Loading textures...
INFO [T1] Loading sounds...
INFO [T1] Loading time  [data]: 4.803 s
INFO Gaia has civilisation Gaia
INFO Jonas has civilisation British
INFO Michael has civilisation French
Traceback (most recent call last):
  File "run.py", line 15, in init run
    main()
  File "/home/sean/Coding/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 133, in main
    return args.entrypoint(args, cli.error)
  File "/home/sean/Coding/openage/.bin/g++-debug-Oauto-sanitize-none/openage/game/main.py", line 78, in main
    return run_game(args, root)
  File "openage/game/main_cpp.pyx", line 47, in openage.game.main_cpp.run_game
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x56b
  File "", line 0, in openage::Engine::run()+0x27
  File "", line 0, in openage::Engine::loop()+0xaa
  File "", line 0, in openage::gui::GUI::on_input(SDL_Event*)+0x10
  File "", line 0, in qtsdl::GuiInput::process(SDL_Event*)+0xc
  File "", line 0, in qtsdl::GuiInputImpl::process(SDL_Event*)+0x3d0
  File "", line 0, in qtsdl::GuiInputImpl::relay_input_event(QEvent*, bool)+0x51
  File "", line 0, in qtsdl::GuiInputImpl::input_event(std::atomic<bool>*, QEvent*, bool)+0x7a
  File "", line 0, in 
  File "", line 0, in QtPrivate::QSlotObject<void (qtsdl::EventHandlingQuickWindow::*)(std::atomic<bool>*, QEvent*, bool), QtPrivate::List<std::atomic<bool>*, QEvent*, bool>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)+0x61
  File "", line 0, in qtsdl::EventHandlingQuickWindow::on_input_event(std::atomic<bool>*, QEvent*, bool)+0x4b
  File "", line 0, in QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x12a
  File "", line 0, in QWindow::event(QEvent*)+0x125
  File "", line 0, in QQuickWindowPrivate::deliverPointerEvent(QQuickPointerEvent*)+0x6c
  File "", line 0, in QQuickWindowPrivate::deliverMouseEvent(QQuickPointerMouseEvent*)+0x188
  File "", line 0, in QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x12a
  File "", line 0, in QQuickItem::event(QEvent*)+0x118
  File "", line 0, in QQuickMouseArea::mouseReleaseEvent(QMouseEvent*)+0x94
  File "", line 0, in QQuickMouseArea::setPressed(Qt::MouseButton, bool, Qt::MouseEventSource)+0x1f6
  File "", line 0, in QQuickMouseArea::released(QQuickMouseEvent*)+0x43
  File "", line 0, in 
  File "", line 0, in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**)+0x23d
  File "", line 0, in 
  File "", line 0, in QQmlBoundSignalExpression::evaluate(void**)+0x34d
  File "", line 0, in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*)+0x226
  File "", line 0, in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*)+0x16e
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const+0x5da
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in 
  [Previous line repeated 2 more times]
  File "", line 0, in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**)+0x23d
  File "", line 0, in 
  File "", line 0, in QQmlBoundSignalExpression::evaluate(void**)+0x34d
  File "", line 0, in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*)+0x226
  File "", line 0, in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*)+0x16e
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const+0x5da
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**)+0x102b
  File "", line 0, in 
  File "", line 0, in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**)+0x23d
  File "", line 0, in 
  File "", line 0, in QQmlBoundSignalExpression::evaluate(void**)+0x34d
  File "", line 0, in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*)+0x226
  File "", line 0, in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*)+0x16e
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const+0x5da
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in openage::gui::GameCreator::qt_metacall(QMetaObject::Call, int, void**)+0x45
  File "", line 0, in 
  File "", line 0, in openage::gui::GameCreator::activate()+0x239
  File "", line 0, in qtsdl::GameLogicCaller::in_game_logic_thread(std::function<void ()> const&) const+0x3e
  File "", line 0, in 
  File "", line 0, in QtPrivate::QSlotObject<void (qtsdl::GuiCallback::*)(std::function<void ()> const&), QtPrivate::List<std::function<void ()> const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)+0x4f
  File "", line 0, in qtsdl::GuiCallback::process(std::function<void ()> const&)+0xc
  File "", line 0, in std::function<void ()>::operator()() const+0xe
  File "", line 0, in 
  File "", line 0, in openage::Generator::create(std::shared_ptr<openage::GameSpec>)+0x293
  File "", line 0, in openage::GameMain::GameMain(openage::Generator const&)+0x421
  File "", line 0, in openage::Generator::add_units(openage::GameMain&) const+0x91
  File "", line 0, in openage::UnitContainer::new_unit(openage::UnitType&, openage::Player&, openage::coord::phys3)+0xee
  File "", line 0, in openage::ObjectProducer::place(openage::Unit*, std::shared_ptr<openage::Terrain>, openage::coord::phys3) const+0x5bc
  File "", line 0, in openage::TerrainObject::place(std::shared_ptr<openage::Terrain> const&, openage::coord::phys3&, openage::object_state)+0x45
  File "", line 0, in std::function<bool (openage::coord::phys3 const&)>::operator()(openage::coord::phys3 const&) const+0xe
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in openage::SquareObject::intersects(openage::TerrainObject const&, openage::coord::phys3 const&) const+0x33c
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x1b2
  File "libopenage/terrain/terrain_object.cpp", line 363, in virtual bool openage::SquareObject::intersects(const openage::TerrainObject&, const openage::coord::phys3&) const
    throw Error{ERR << "object is not associated to a valid terrain"};
openage.cppinterface.exctranslate.CPPException: object is not associated to a valid terrain
make: *** [Makefile:25: run] Error 1
```

This doesn't happen when I edit the seed to something else, like 4320. When I run with a changed seed, everything seems to run fine as far as I can tell.

**Comment by heinezen** [comment]
That is very weird. Which version of AoE2 did you use for conversion? Looks like it tried to place a terrain that does not exist or did not get converted properly.

**Comment by SeanRamey** [comment]
I used the Steam HD version with patch43 (i think that's what it's called, but it's like version 4.3 selected from the betas in steam)

**Comment by heinezen** [comment]
Just tested it and this also happens for basic AoC 1.0c. Looks like the engine's terrain generator, specifically the blending routine, cannot handle the seed.

**Comment by SeanRamey** [comment]
@heinezen What would a typical seed for the game look like? Does it regularly generate 4 number seeds? Also, is the seed only using the 1 - 9 digits, or can it be hexadecimal and use letters too?

**Comment by heinezen** [comment]
I think the problem in this case is that the seed is not used to generate the whole map (we have no full map generator currently). The generator first chooses the player starting positions and then uses the seed to places terrain chunks around them. Determining the starting positions seems to be slightly off due to float rounding which is probably the result of compiler optimizations. This is usually fine, as you just get a slightly different map that works and that's just as usable for testing as the others. However, this time the generation produced a map that crashes the engine when it places the starting units.

So after digging a bit into the issue I think this is what happened:

* The engine generates the terrain
* It tries to place the town center at the player's starting position
* Placing the town center replaces the underlying terrain to the "Foundation" terrain type
* The intersection/blending for the new terrain has to be calculated

For some reason the last step fails. Might be a race condition that results in the terrain_ptr returning the nullptr.

**Comment by okias** [comment]
I can confirm with AoE 1.0c Conquerors with 0.4.1.

**Comment by TheJJ** [comment]
With the new gamestate simulation this shouldn't be a problem any more!
