### ISSUE TITLE
No module named 'readline'

### ISSUE THREAD

**Issue by donno2048** [SFTtech/openage#1323]
I get this error when running openage:
```py
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\openage\python\openage\__main__.py", line 140, in <module>
    sys.exit(main())
  File "C:\openage\python\openage\__main__.py", line 87, in main
    from .convert.main import init_subparser
  File "C:\openage\python\openage\convert\main.py", line 7, in <module>
    import readline  # pylint: disable=unused-import
ModuleNotFoundError: 
```
on windows 10

**Comment by donno2048** [comment]
I ran `pip install readline` but got:
```py
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\elisha\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Elisha\\AppData\\Local\\Temp\\pip-install-l40fb5tv\\readline\\setup.py'"'"'; __file__='"'"'C:\\Users\\Elisha\\AppData\\Local\\Temp\\pip-install-l40fb5tv\\readline\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Elisha\AppData\Local\Temp\pip-pip-egg-info-43lt0umv'
         cwd: C:\Users\Elisha\AppData\Local\Temp\pip-install-l40fb5tv\readline\
    Complete output (1 lines):
    error: this module is not meant to work on Windows
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by heinezen** [comment]
We should switch to this: https://pypi.org/project/pyreadline/

**Comment by TheJJ** [comment]
It's part of the guide: https://github.com/SFTtech/openage/blob/d73cf2e7172f9b3efd5a5ff0404dc43df16e757e/doc/build_instructions/windows_msvc.md#python-modules

Did you install `pyreadline`?

**Comment by donno2048** [comment]
I actually just installed it directly from Bintray...

Why is this happening if it's supposed to use `pyreadline` anyway?

**Comment by TheJJ** [comment]
I'm not very sure but i think `pyreadline` injects readline behavior, and provides the `import readline` for windows.
