### ISSUE TITLE
[convert assets] AttributeError: 'UnionPath' object has no attribute 'debug_info'

### ISSUE THREAD

**Issue by okias** [SFTtech/openage#1350]
```
INFO [py] launching openage v0.4.1-371-g0c6e704b
INFO [py] compiled by GNU 10.2.0
  Do you want to convert assets? [Y/n]
> y
Traceback (most recent call last):
  File "/app/bin/openage", line 15, in <module>
    main()
  File "/app/lib/python3.8/site-packages/openage/__main__.py", line 132, in main
    return args.entrypoint(args, cli.error)
  File "/app/lib/python3.8/site-packages/openage/game/main.py", line 68, in main
    used_asset_path = convert_assets(root["assets"], root["cfg"], args,
  File "/app/lib/python3.8/site-packages/openage/convert/main.py", line 52, in convert_assets
    debug_cli_args(args.debugdir, args.debug_info, args)
AttributeError: 'UnionPath' object has no attribute 'debug_info'
```

**Comment by TobiasFP** [comment]
This has to do with the new gamestate not fully in place. and relates to string_resources.docx, gamedata.docx, player_palette.docx and termcolors.docx (This one in particular relates to the termcolors.docx.
