### ISSUE TITLE
Tokenizing empiresdat led to xx columns (expected 49)!

### ISSUE THREAD

**Issue by okias** [SFTtech/openage#1351]
Flatpak build, data converted with 0.4.1. Ignore wayland warnings, it's harmless.

```
Application started at 18:00:05
INFO [py] launching openage v0.4.1-371-g84bff8df
INFO [py] compiled by GNU 10.2.0
  Do you want to convert assets? [Y/n]
> n
INFO launching engine with Path(Union(<openage.util.fslike.union.Union object at 0x7f396d8939d0>.root @ (b'cfg',), <openage.util.fslike.union.Union object at 0x7f396d893430>.root @ (b'assets',)):) and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=2, samples=4096]
INFO Initialized SDL video subsystems.
 ERR Failed to create wl_display (No such file or directory)
INFO Could not load the Qt platform plugin "wayland" in "" even though it was found.
(python3:3): GLib-GIO-DEBUG: 18:00:09.393: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
INFO Compiled with Qt 5.15.2 and run with Qt 5.15.2
INFO loading configuration files...
INFO [py] loading config file [Union(<openage.util.fslike.union.Union object at 0x7f396d8939d0>.root @ (b'cfg',), <openage.util.fslike.union.Union object at 0x7f396d893430>.root @ (b'assets',))]:cfg/keybinds.oac...
INFO Loading time [engine]: 1.034 s
INFO Loading time   [game]: 1.064 s
INFO [T1] Loading game specification files...
INFO [T1] Loaded multi-csv file: 45484 sub-files
WARN [T2] ImageProvider was stopped during the load, so it'll appear like the requestTexture() isn't implemented.
WARN [T2] ImageProvider supports Texture type but has not implemented requestTexture()
Traceback (most recent call last):
  File "/app/bin/openage", line 15, in <module>
    main()
  File "/app/lib/python3.8/site-packages/openage/__main__.py", line 132, in main
    return args.entrypoint(args, cli.error)
  File "/app/lib/python3.8/site-packages/openage/game/main.py", line 79, in main
    return run_game(args, root)
  File "openage/game/main_cpp.pyx", line 47, in openage.game.main_cpp.run_game
  File "", line 0, in 
  File "", line 0, in 
  File "", line 0, in openage::job::Worker::process()+0x1a9
  File "", line 0, in openage::job::Worker::execute_job(std::shared_ptr<openage::job::JobStateBase>&)+0x57
  File "", line 0, in openage::job::TypedJobStateBase<bool>::execute(std::function<bool ()>)+0x67
  File "", line 0, in openage::GameSpec::initialize()+0x895
  File "", line 0, in 
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x1e4
  File "libopenage/gamedata/gamedata.gen.cpp", line 25, in int openage::gamedata::empiresdat::fill(const string&)
openage.cppinterface.exctranslate.CPPException: Tokenizing empiresdat led to 26 columns (expected 49)!
Application exited
```

**Comment by TheJJ** [comment]
This error is a discrepancy between the converted (old format) data and the generated parsing code. Since we got rid of the csvs in favor of nyan, it's not worth fixing this error :)

**Comment by okias** [comment]
Ok, can be this somehow be propagated to the user more expressively (imagine user upgrading from 0.4.1 to 0.5.x)? Like warning saying "You're using old data format, please remove and update"?

**Comment by TheJJ** [comment]
That's what is done #1352 :)

**Comment by okias** [comment]
You can references bugs in PR/MR's users can nicely track what's related to what. Also "Closes: bug_url" automatically closes bug when PR is merged.

Thank you! :)
