### ISSUE TITLE
Converter crash "FileNotFoundError(b'/'.join(parts))"

### ISSUE THREAD

**Issue by okias** [SFTtech/openage#1353]
After applying PR https://github.com/SFTtech/openage/pull/1352 , I got further, but still conventer crashes in next step. With exactly identical game directory converter worked well with `0.4.1`.
```
Application started at 14:27:49
INFO [py] launching openage v0.4.1-371-g84bff8df
INFO [py] compiled by GNU 10.2.0
  Do you want to convert assets? [Y/n]
> y

Please select an Age of Kings installation directory.
Insert the index of one of the proposals, or any path:
(0) /home/username/Mygames/aoe2
> 
converting from '/home/username'
Traceback (most recent call last):
  File "/app/bin/openage", line 15, in <module>
    main()
  File "/app/lib/python3.8/site-packages/openage/__main__.py", line 132, in main
    return args.entrypoint(args, cli.error)
  File "/app/lib/python3.8/site-packages/openage/game/main.py", line 69, in main
    used_asset_path = convert_assets(
  File "/app/lib/python3.8/site-packages/openage/convert/main.py", line 68, in convert_assets
    args.avail_game_eds, args.avail_game_exps = create_version_objects(auxiliary_files_dir)
  File "/app/lib/python3.8/site-packages/openage/convert/service/init/version_detect.py", line 74, in create_version_objects
    with game_edition_path.open() as game_edition_toml:
  File "/app/lib/python3.8/site-packages/openage/util/fslike/path.py", line 112, in open
    handle = self.fsobj.open_r(self.parts)
  File "/app/lib/python3.8/site-packages/openage/util/fslike/union.py", line 111, in open_r
    raise FileNotFoundError(b'/'.join(parts))
FileNotFoundError: b'cfg/converter/games/game_editions.toml'
Application exited
```

**Comment by heinezen** [comment]
That's weird because `cfg/converter/games/game_editions.toml` is a file from the repo and should definitely show up. It ran perfectly through on my end too, but I'll test again.

**Comment by heinezen** [comment]
Followed the same steps after fetching your PR, but I don't get the error. Strange.

What is weird is the terminal output you got here:

```
(0) /home/username/Mygames/aoe2
> 
converting from '/home/username'
```

It should say `converting from '/home/username/Mygames/aoe2'` (the full path). Maybe there's something wrong with this.

**Comment by okias** [comment]
I used cached value, but I'll try to write full path again...

**Comment by okias** [comment]
when I explicitly write the path again, it shows whole path, but fails same way.

**Comment by heinezen** [comment]
Fixed by https://github.com/SFTtech/openage/pull/1352
