### ISSUE TITLE
KeyError: 208

### ISSUE THREAD

**Issue by LinuxDonald** [SFTtech/openage#1355]
```
INFO [py] launching openage v0.4.1-377-g2be30ba76
INFO [py] compiled by GNU 10.2.0
  Do you want to convert assets? [Y/n]
> Y
  Should we call wine to determine an AOE installation? [Y/n]
> n
Could not find any installation directory automatically.
Please enter an AOE2 install path manually.
> /home/schatzi/nvme/Steam/steamapps/common/AoE2DE/
converting from '/home/schatzi/nvme/Steam/steamapps/common/AoE2DE'
INFO [py] Game edition detected:
INFO [py]  * Age of Empires 2: Definitive Edition
INFO [py] converting metadata
INFO [py] [0] palette
INFO [py] [1] empires.dat
INFO [py] Starting conversion...
INFO [py] Extracting Genie data...
INFO [py] Creating API-like objects...
INFO [py] Linking API-like objects...
INFO [py] Generating auxiliary objects...
INFO [py] Creating nyan objects...
Traceback (most recent call last):
  File "/usr/bin/openage", line 15, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/openage/__main__.py", line 132, in main
    return args.entrypoint(args, cli.error)
  File "/usr/lib/python3.9/site-packages/openage/game/main.py", line 71, in main
    used_asset_path = convert_assets(
  File "/usr/lib/python3.9/site-packages/openage/convert/main.py", line 100, in convert_assets
    for current_item in convert(args):
  File "/usr/lib/python3.9/site-packages/openage/convert/tool/driver.py", line 48, in convert
    yield from convert_metadata(args)
  File "/usr/lib/python3.9/site-packages/openage/convert/tool/driver.py", line 96, in convert_metadata
    modpacks = args.converter.convert(gamespec,
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/processor.py", line 63, in convert
    modpacks = cls._post_processor(dataset)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/processor.py", line 153, in _post_processor
    DE2NyanSubprocessor.convert(full_data_set)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/nyan_subprocessor.py", line 38, in convert
    cls._process_game_entities(gamedata)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/nyan_subprocessor.py", line 120, in _process_game_entities
    cls.tech_group_to_tech(tech_group)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/nyan_subprocessor.py", line 596, in tech_group_to_tech
    patches.extend(DE2TechSubprocessor.get_patches(tech_group))
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/tech_subprocessor.py", line 147, in get_patches
    patches.extend(cls.resource_modify_effect(converter_group,
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/tech_subprocessor.py", line 276, in resource_modify_effect
    upgrade_func = DE2TechSubprocessor.upgrade_resource_funcs[resource_id]
KeyError:  208
```

**Comment by heinezen** [comment]
Thx. Should be fixed in https://github.com/SFTtech/openage/pull/1356

**Comment by LinuxDonald** [comment]
openage
INFO [py] launching openage v0.4.1-397-g4d76ce017
INFO [py] compiled by GNU 10.2.0
  Do you want to convert assets? [Y/n]
> y
  Should we call wine to determine an AOE installation? [Y/n]
> n
Could not find any installation directory automatically.
Please enter an AOE2 install path manually.
> /home/schatzi/nvme/Steam/steamapps/common/AoE2DE/
converting from '/home/schatzi/nvme/Steam/steamapps/common/AoE2DE'
INFO [py] Game edition detected:
INFO [py]  * Age of Empires 2: Definitive Edition
INFO [py] converting metadata
INFO [py] [0] palette
INFO [py] [1] empires.dat
INFO [py] using cached wrapper: /tmp/empires2_x2_p1.dat.pickle
INFO [py] Starting conversion...
INFO [py] Extracting Genie data...
INFO [py] Creating API-like objects...
INFO [py] Linking API-like objects...
INFO [py] Generating auxiliary objects...
INFO [py] Creating nyan objects...
Traceback (most recent call last):
  File "/usr/bin/openage", line 15, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/openage/__main__.py", line 132, in main
    return args.entrypoint(args, cli.error)
  File "/usr/lib/python3.9/site-packages/openage/game/main.py", line 71, in main
    used_asset_path = convert_assets(
  File "/usr/lib/python3.9/site-packages/openage/convert/main.py", line 100, in convert_assets
    for current_item in convert(args):
  File "/usr/lib/python3.9/site-packages/openage/convert/tool/driver.py", line 48, in convert
    yield from convert_metadata(args)
  File "/usr/lib/python3.9/site-packages/openage/convert/tool/driver.py", line 96, in convert_metadata
    modpacks = args.converter.convert(gamespec,
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/processor.py", line 63, in convert
    modpacks = cls._post_processor(dataset)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/processor.py", line 153, in _post_processor
    DE2NyanSubprocessor.convert(full_data_set)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/nyan_subprocessor.py", line 38, in convert
    cls._process_game_entities(gamedata)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/nyan_subprocessor.py", line 126, in _process_game_entities
    cls.civ_group_to_civ(civ_group)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/nyan_subprocessor.py", line 886, in civ_group_to_civ
    civ_setup = DE2CivSubprocessor.get_civ_setup(civ_group)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/civ_subprocessor.py", line 32, in get_civ_setup
    patches.extend(cls.setup_civ_bonus(civ_group))
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/civ_subprocessor.py", line 59, in setup_civ_bonus
    bonus_patches = DE2TechSubprocessor.get_patches(civ_bonus)
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/tech_subprocessor.py", line 148, in get_patches
    patches.extend(cls.resource_modify_effect(converter_group,
  File "/usr/lib/python3.9/site-packages/openage/convert/processor/conversion/de2/tech_subprocessor.py", line 277, in resource_modify_effect
    upgrade_func = DE2TechSubprocessor.upgrade_resource_funcs[resource_id]
KeyError: 94

**Comment by heinezen** [comment]
@LinuxDonald fixed in https://github.com/SFTtech/openage/pull/1359
