### ISSUE TITLE
no valid converter found for game edition Age of Empires 2: Age of Kings

### ISSUE THREAD

**Issue by laenion** [SFTtech/openage#1419]
When trying to use openage with the German retail version of _Age of Empires II: The Age of Kings_ from the _Age of Empires II: Gold Edition_, then the asset conversion fails with the following output:

```
$ bin/run
INFO [py] launching openage v0.4.1-661-g1c274a54
INFO [py] compiled by Clang 12.0.1
INFO [py] running in DEVMODE
  Do you want to convert assets? [Y/n]
> 
Could not find any installation directory automatically.
Please enter an AOE2 install path manually.
> /usr/local/enginedata/Age of Empires II
converting from '/usr/local/enginedata/Age of Empires II'
INFO [py] Looking for compatible games to convert...
INFO [py] Compatible game edition detected:
INFO [py]  * Age of Empires 2: Age of Kings
INFO [py] converting metadata
INFO [py] [0] palette
Traceback (most recent call last):
  File "run.py", line 15, in init run
    main()
  File "/mnt/images/Medienarchiv/Download/Open-Source-Engines/openage/.bin/clang++-release-Oauto-sanitize-none/openage/__main__.py", line 143, in main
    return args.entrypoint(args, cli.error)
  File "/mnt/images/Medienarchiv/Download/Open-Source-Engines/openage/.bin/clang++-release-Oauto-sanitize-none/openage/game/main.py", line 82, in main
    used_asset_path = convert_assets(
  File "/mnt/images/Medienarchiv/Download/Open-Source-Engines/openage/.bin/clang++-release-Oauto-sanitize-none/openage/convert/main.py", line 103, in convert_assets
    for current_item in convert(args):
  File "/mnt/images/Medienarchiv/Download/Open-Source-Engines/openage/.bin/clang++-release-Oauto-sanitize-none/openage/convert/tool/driver.py", line 30, in convert
    yield from convert_metadata(args)
  File "/mnt/images/Medienarchiv/Download/Open-Source-Engines/openage/.bin/clang++-release-Oauto-sanitize-none/openage/convert/tool/driver.py", line 62, in convert_metadata
    args.converter = get_converter(args.game_version)
  File "/mnt/images/Medienarchiv/Download/Open-Source-Engines/openage/.bin/clang++-release-Oauto-sanitize-none/openage/convert/tool/driver.py", line 147, in get_converter
    raise Exception(f"no valid converter found for game edition {game_edition.edition_name}")
Exception: no valid converter found for game edition Age of Empires 2: Age of Kings
```

I've tried to extract the game files with cabextract directly from disc, used the installation directory from a Windows 98 machine as a source and tried with and without copying the data files from disc into the game directory, with all variants resulting in the same message.

Should this version work with the engine / am I doing something wrong here?

**Comment by heinezen** [comment]
Age of Empires II: The Age of Kings (without the expansion The Conquerors) is unsupported. The reason is that the data formats between the base game and the expansion is different and we figured that most people own the expansion anyway. Actually, *The Conquerors* is part of the Gold Edition too, so you should extract its files and copy them into the same installation directory as the base game. Then it should work.

However, you actually found another bug :D The converter should detect that *Age of Kings* is unsupported and give you a nice list of supported versions. But there is a crucial check missing, so it tries to start the conversion instead of ending gracefully. https://github.com/SFTtech/openage/pull/1420 should fix the problem.

**Comment by heinezen** [comment]
https://github.com/SFTtech/openage/pull/1420 should fix the missing error handling :)
