### ISSUE TITLE
Rise of Rome error: Requested modpack 'engine' not available.

### ISSUE THREAD

**Issue by Hewitt1410** [SFTtech/openage#1530]
I run in DEV mode and it fails like below:
```
python3 -m openage
INFO [py] launching openage v0.4.1-1388-g58cb4d74
INFO [py] compiled by GNU 11.4.0
INFO [py] running in DEVMODE
  Do you want to convert assets? [Y/n]
> y
  Should we call wine to determine an AOE installation? [Y/n]
> n

Please select an Age of Empires installation directory.
Insert the index of one of the proposals, or any path:
(0) /home/user0/projects/game/aoe/AOE1_played/AOE1
> 0
converting from '/home/user0/projects/game/aoe/AOE1_played/AOE1'
INFO [py] Looking for compatible games to convert...
INFO [py] Compatible game edition detected:
INFO [py]  * Age of Empires 1: Rise of Rome
INFO [py] converting metadata
INFO [py] [0] palette
INFO [py] [1] empires.dat
INFO [py] using cached wrapper: /tmp/ROR_empires.dat.pickle
INFO [py] Starting conversion...
INFO [py] Extracting Genie data...
INFO [py] Creating API-like objects...
INFO [py] Linking API-like objects...
INFO [py] Generating auxiliary objects...
INFO [py] Creating nyan objects...
INFO [py] Creating requests for media export...
INFO [py] Starting export...
INFO [py] Dumping info file...
INFO [py] Dumping data files...
INFO [py] Exporting media files...
INFO [py] -- Exporting graphics files...
INFO [py] -- Exporting terrain files...
INFO [py] -- Exporting sound files...
INFO [py] Dumping metadata files...
INFO [py] [2] player color palette
INFO [py] [3] terminal color palette
INFO [py] [4] game specification files
INFO [py] asset conversion complete; asset version: 7
INFO loading configuration files...
INFO [py] loading config file [Union(Directory(/home/user0/projects/game/aoe/openage/cfg).root @ (b'cfg',), Directory(/home/user0/projects/game/aoe/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
INFO launching engine with root directory >>>>>>>>Path(Union(Directory(/home/user0/projects/game/aoe/openage/cfg).root @ (b'cfg',), Directory(/home/user0/projects/game/aoe/openage/assets).root @ (b'assets',)):)
INFO loading configuration files...
INFO [py] loading config file [Union(Directory(/home/user0/projects/game/aoe/openage/cfg).root @ (b'cfg',), Directory(/home/user0/projects/game/aoe/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
INFO Found modpack: aoe1_base
INFO root_dir >>>>>>>>Path(Union(Directory(/home/user0/projects/game/aoe/openage/cfg).root @ (b'cfg',), Directory(/home/user0/projects/game/aoe/openage/assets).root @ (b'assets',)):)
INFO mod >>>>>>>>aoe1_base
INFO register_modpack: aoe1_base
INFO Created game simulation
INFO modpack_id =engine
INFO modpack_available =aoe1_base
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user0/projects/game/aoe/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 178, in <module>
    sys.exit(main())
  File "/home/user0/projects/game/aoe/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 171, in main
    return args.entrypoint(args, cli.error)
  File "/home/user0/projects/game/aoe/openage/.bin/g++-debug-Oauto-sanitize-none/openage/game/main.py", line 104, in main
    return run_game(args, root)
  File "openage/game/main_cpp.pyx", line 37, in openage.game.main_cpp.run_game
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x241
  File "", line 0, in openage::engine::Engine::Engine(openage::engine::Engine::mode, openage::util::Path const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x917
  File "", line 0, in openage::gamestate::GameSimulation::set_modpacks(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x21e
  File "", line 0, in openage::assets::ModManager::activate_modpacks(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x33
  File "", line 0, in openage::assets::ModManager::set_load_order(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x330
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x1b6
  File "libopenage/assets/mod_manager.cpp", line 52, in void openage::assets::ModManager::set_load_order(const std::vector<std::__cxx11::basic_string<char> >&)
openage.cppinterface.exctranslate.CPPException: Requested modpack 'engine' not available.
```

**Comment by coco875** [comment]
use this command `python3-m openage convert-export-api <assets/converted>`

**Comment by Hewitt1410** [comment]
> use this command `python3-m openage convert-export-api <assets/converted>`
![Screenshot from 2023-08-21 18-45-55](https://github.com/SFTtech/openage/assets/12505538/8bf9d4f0-d76f-4a04-bab2-d6cb4da36751)

Thanks, it works. But it only shows like this, is it error? Or i do wrong some configs?

**Comment by coco875** [comment]
it's normal is not complet done but normally you can click and have the same demo then the last blog post

**Comment by heinezen** [comment]
`engine` is the modpack for the internal openage API. Currently, it has to be exported manually. This will be fixed in future versions where it will be exported automatically on first startup, or directly be delivered with the release.
