### ISSUE TITLE
Errors after the new PR merged

### ISSUE THREAD

**Issue by zoli111** [SFTtech/openage#1615]
I made a build to test the new functionality, but I got the following errors:

```
./run main
INFO [py] launching openage v0.3.0-3059-g28b4b5ac
INFO [py] compiled by GNU 13.2.1
INFO [py] running in DEVMODE
INFO [py] No converted assets have been found
INFO loading configuration files...
INFO [py] loading config file [Union(Directory(/home/zoli/openage/cfg).root @ (b'cfg',), Directory(/home/zoli/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
INFO launching engine with root directoryPath(Union(Directory(/home/zoli/openage/cfg).root @ (b'cfg',), Directory(/home/zoli/openage/assets).root @ (b'assets',)):)
INFO loading configuration files...
INFO [py] loading config file [Union(Directory(/home/zoli/openage/cfg).root @ (b'cfg',), Directory(/home/zoli/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
INFO Found modpack: hd_base
INFO Created game simulation
Traceback (most recent call last):
  File "run.py", line 20, in init run
    main()
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 171, in main
    return args.entrypoint(args, cli.error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/main/main.py", line 96, in main
    return run_game(args, root)
           ^^^^^^^^^^^^^^^^^^^^
  File "openage/main/main_cpp.pyx", line 46, in openage.main.main_cpp.run_game
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0xab
  File "", line 0, in openage::engine::Engine::Engine(openage::engine::Engine::mode, openage::util::Path const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x1de
  File "", line 0, in openage::gamestate::GameSimulation::set_modpacks(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0xb0
  File "", line 0, in openage::assets::ModManager::activate_modpacks(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x2f
  File "", line 0, in openage::assets::ModManager::set_load_order(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0xdb
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0xba
  File "libopenage/assets/mod_manager.cpp", line 41, in void openage::assets::ModManager::set_load_order(const std::vector<std::__cxx11::basic_string<char> >&)
openage.cppinterface.exctranslate.CPPException: Requested modpack 'engine' not available.
```

```
./run convert
  Do you want to convert assets? [Y/n]
> y
Could not find any installation directory automatically.
Please enter an AOE2 install path manually.
> /hdd/SteamLibrary/steamapps/common/Age2HD/
converting from '/hdd/SteamLibrary/steamapps/common/Age2HD'
INFO [py] Looking for compatible games to convert...
INFO [py] Compatible game edition detected:
INFO [py]  * Age of Empires 2: HD Edition
INFO [py] converting metadata
INFO [py] [0] palette
INFO [py] [1] empires.dat
INFO [py] using cached wrapper: /tmp/HDEDITION_empires2_x1_p1.dat.pickle
INFO [py] Starting conversion...
INFO [py] Extracting Genie data...
INFO [py] Creating API-like objects...
INFO [py] Linking API-like objects...
INFO [py] Generating auxiliary objects...
INFO [py] Creating nyan objects...
INFO [py] Creating requests for media export...
INFO [py] Starting export...
INFO [py] Dumping info file...
INFO [py] Dumping data files...
INFO [py] Exporting media files...
INFO [py] -- Exporting graphics files...
INFO [py] -- Exporting terrain files...
INFO [py] -- Exporting sound files...
INFO [py] Dumping metadata files...
Traceback (most recent call last):
  File "run.py", line 20, in init run
    main()
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/__main__.py", line 171, in main
    return args.entrypoint(args, cli.error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/main.py", line 245, in main
    if not convert_assets(outdir, args, srcdir):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/main.py", line 115, in convert_assets
    for current_item in convert(args):
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/tool/driver.py", line 38, in convert
    yield from convert_metadata(args)
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/tool/driver.py", line 99, in convert_metadata
    ModpackExporter.export(modpack, args)
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/processor/export/modpack_exporter.py", line 65, in export
    DataExporter.export(modpack.get_metadata_files(), modpack_dir)
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/processor/export/data_exporter.py", line 35, in export
    output_content = data_file.dump()
                     ^^^^^^^^^^^^^^^^
  File "/home/zoli/openage/.bin/g++-debug-Oauto-sanitize-none/openage/convert/entity_object/export/metadata_export.py", line 161, in dump
    texture_file.set_size(self.size[0], self.size[1])
                          ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by heinezen** [comment]
Are you sure you are using the new version? In your log messages it says

```
INFO [py] launching openage v0.3.0-3059-g28b4b5ac
```

which is rather old. The current master should show version `v0.5.3-56-gc4ccd415`. Also, the log messages don't really match up with what should be logged in the current version.

**Comment by zoli111** [comment]
It's interesting, because I made a fresh clone from the GitHub repo. Investigating...

**Comment by zoli111** [comment]
I have no idea what went wrong. I cloned again and now the game shows `v0.5.3-56-gc4ccd415` as version, and it also runs without errors. Thank you for the guidance.
