### ISSUE TITLE
Better error messages for media convert script

### ISSUE THREAD

**Issue by LordAro** [SFTtech/openage#281]
Currently the current error messages (raw python stacktraces) aren't exactly the most user friendly

See:

```
buildsystem/runinenv PYTHONPATH=prependpath:py -- python3 -m openage.convert -v media -o "assets/converted" "./aoe2" graphics:*.* terrain:*.* sounds0:*.* sounds1:*.* gamedata0:*.* gamedata1:*.* gamedata2:*.* interface:*.*
age2 input directory: ./aoe2
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lunavorax/Documents/Code/openage/py/openage/convert/__main__.py", line 71, in <module>
    main()
  File "/home/lunavorax/Documents/Code/openage/py/openage/convert/__main__.py", line 68, in main
    args.handler(args)
  File "/home/lunavorax/Documents/Code/openage/py/openage/convert/mediafile.py", line 112, in media_convert
    palette_data = drsfiles["interface"].get_file_data('bin', palette_id)
KeyError: 'interface'
Makefile:37: recipe for target 'media' failed
make: *** [media] Error 1
```

(Empty directory)

```
buildsystem/runinenv PYTHONPATH=prependpath:py -- python3 -m openage.convert -v media -o "assets/converted" "./aoe2" graphics:*.* terrain:*.* sounds0:*.* sounds1:*.* gamedata0:*.* gamedata1:*.* gamedata2:*.* interface:*.*
age2 input directory: ./aoe2
DRS header [graphics.drs]
  copyright:          Copyright (c) 1997 Ensemble Studios.
  version:            1.00
  ftype:              tribe
  table count:        1
  file offset:        17404

DRS header [interfac.drs]
  copyright:          Copyright (c) 1997 Ensemble Studios.
  version:            1.00
  ftype:              tribe
  table count:        3
  file offset:        3820

DRS header [terrain.drs]
  copyright:          Copyright (c) 1997 Ensemble Studios.
  version:            1.00
  ftype:              tribe
  table count:        1
  file offset:        328

DRS header [sounds.drs]
  copyright:          Copyright (c) 1997 Ensemble Studios.
  version:            1.00
  ftype:              tribe
  table count:        1
  file offset:        12328

DRS header [gamedata.drs]
  copyright:          Copyright (c) 1997 Ensemble Studios.
  version:            1.00
  ftype:              tribe
  table count:        1
  file offset:        652

storing files to assets/converted
reading blendomatic data from aoe2/DATA/blendomatic.dat
saving blending mode00 texture -> assets/converted/blendomatic.dat/mode00.png
saving assets/converted/blendomatic.dat/mode00.docx..
saving assets/converted/blendomatic.dat/mode00.png..
saving blending mode01 texture -> assets/converted/blendomatic.dat/mode01.png
saving assets/converted/blendomatic.dat/mode01.png..
saving assets/converted/blendomatic.dat/mode01.docx..
saving blending mode02 texture -> assets/converted/blendomatic.dat/mode02.png
saving assets/converted/blendomatic.dat/mode02.png..
saving assets/converted/blendomatic.dat/mode02.docx..
saving blending mode03 texture -> assets/converted/blendomatic.dat/mode03.png
saving assets/converted/blendomatic.dat/mode03.docx..
saving assets/converted/blendomatic.dat/mode03.png..
blending masks exported successfully!
PE file [aoe2/LANGUAGE.DLL]
DOS header: (b'PE\x00\x00', 332, 5, 936789929, 0, 0, 224, 8462)
  Optional header: (267, 6, 0, 12288, 569344, 0, 4329, 4096, 16384, 268435456, 4096, 4096, 4, 0, 0, 0, 4, 0, 0, 585728, 4096, 593969, 2, 0, 1048576, 4096, 1048576, 4096, 0, 16)
  fr_FR: 4952 resource strings
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lunavorax/Documents/Code/openage/py/openage/convert/__main__.py", line 71, in <module>
    main()
  File "/home/lunavorax/Documents/Code/openage/py/openage/convert/__main__.py", line 68, in main
    args.handler(args)
  File "/home/lunavorax/Documents/Code/openage/py/openage/convert/mediafile.py", line 157, in media_convert
    lpath = util.ifilepath(args.srcdir, l)
  File "/home/lunavorax/Documents/Code/openage/py/openage/util.py", line 113, in ifilepath
    raise e from None
  File "/home/lunavorax/Documents/Code/openage/py/openage/util.py", line 109, in ifilepath
    realcase = ifilename(basepath, p)
  File "/home/lunavorax/Documents/Code/openage/py/openage/util.py", line 87, in ifilename
    ) from None
FileNotFoundError: could not find 'language_x1.dll' in './aoe2' case-insensitively
Makefile:37: recipe for target 'media' failed
make: *** [media] Error 1
```

(AoEII only, no Conquerors)
##

**Comment by TheJJ** [comment]
the convert output is now totally different, but the error messages are probably not much better.

**Comment by TheJJ** [comment]
The error messages have improved lately, so this should be good. If not, please complain :)
