### ISSUE TITLE
Rendering of buildings broken under r300g/Mobility FireGL V5250 (poor driver/hardware support?)

### ISSUE THREAD

**Issue by oldlaptop** [SFTtech/openage#33]
Buildings simply do not render under r300g (on a Mobility FireGL V5250, like Radeon X1700) : http://plantmonster.net/~oldlaptop/images/openage-blackbuilding.png

The following fragment of console log seems relevant:

```
r300 FP: Compiler Error:
../../../../../../src/gallium/drivers/r300/compiler/r500_fragprog_emit.c::emit_paired():  emit_alu: Too many instructions
Using a dummy shader instead.
```

Whether this can or should be fixed on openage's end, I don't know. Perhaps it's even a hardware limitation.
##

**Comment by TheJJ** [comment]
is this still an issue? mesa should have advanced a lot since back then.

**Comment by TheJJ** [comment]
stil broken, but at some other place now:
```
    INFO Loading time  [data]: 476.962 s
    Traceback (most recent call last):
      File "run.py", line 15, in init run (/home/peter/projects/openage/run.cpp:810)
        main()
      File "/home/peter/projects/openage/openage/__main__.py", line 87, in main
        return args.entrypoint(args, cli.error)
      File "/home/peter/projects/openage/openage/game/main.py", line 39, in main
        return run_game(args, assets)
      File "openage/game/main_cpp.pyx", line 20, in openage.game.main_cpp.run_game (/home/peter/projects/openage/openage/game/main_cpp.cpp:845)
        result = run_game_cpp(args_cpp)
      File "libopenage/util/opengl.cpp", line 66, in void openage::util::gl_check_error()
        throw Error(MSG(err) <<
    openage.cppinterface.exctranslate.CPPException: OpenGL error state after running draw method: 1281
            invalid value passed to opengl call
```

**Comment by TheJJ** [comment]
Now that we have multiple FBOs and render a Qt GUI into one of them, you may wanna test again :P

**Comment by Linkaan** [comment]
I get a similar error as above running on a 64bit kubuntu 16.04.1 with a GeForce GTX 460 graphics card. I get `invalid operation performed during some state` instead of `invalid value passed to opengl call`. The full error looks like:
```
INFO [T1] Loading meta file: ./assets/converted/terrain/15001.slp.docx
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/linkan/openage/run.cpp:891)
    main()
  File "/home/linkan/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/home/linkan/openage/openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (/home/linkan/openage/openage/game/main_cpp.cpp:989)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x55f
  File "", line 0, in openage::Engine::run()+0x1f
  File "", line 0, in openage::Engine::loop()+0x430
  File "", line 0, in openage::util::gl_check_error()+0x165
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x185
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0x9f
  File "libopenage/util/opengl.cpp", line 66, in void openage::util::gl_check_error()
    throw Error(MSG(err) <<
openage.cppinterface.exctranslate.CPPException: OpenGL error state after running draw method: 1282
        invalid operation performed during some state
Segmenteringsfel (minnesutskrift skapad)
```
Any work around for this problem?

**Comment by ChipmunkV** [comment]
Try to run it like that to get more info:

    ./run game --gl-debug

**Comment by zuntrax** [comment]
We'll get rid of our current renderer soon, closing.
