### ISSUE TITLE
Another version of AOE II HD undetected

### ISSUE THREAD

**Issue by divinoro** [SFTtech/openage#438]
Hi, I've downloaded some random version (just like to test you engine) and found new combination for detection:

``` python
age2_hd = (
    "Forgotten Empires HD",
    True,
    {'AoK HD.exe', 'data/empires2_x1.dat'},
)
```

Hope it does help someone. If you tell me how to find version, I'll check it.

Thank you.

**Comment by divinoro** [comment]
Unfortunately resources are not found during extraction:

Traceback (most recent call last):
  File "run.py", line 15, in init run (/var/tmp/openage/run.cpp:796)
    main()
  File "/var/tmp/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/var/tmp/openage/openage/game/main.py", line 33, in main
    if not convert_assets(assets, args):
  File "/var/tmp/openage/openage/convert/main.py", line 123, in convert_assets
    for current_item in convert(args):
  File "/var/tmp/openage/openage/convert/driver.py", line 102, in convert
    yield from convert_metadata(args)
  File "/var/tmp/openage/openage/convert/driver.py", line 155, in convert_metadata
    stringres = get_string_resources(args.srcdir)
  File "/var/tmp/openage/openage/convert/driver.py", line 39, in get_string_resources
    for lang in srcdir["resources"].list():
  File "/var/tmp/openage/openage/util/fslike/path.py", line 90, in list
    yield from self.fsobj.list(self.parts)
  File "/var/tmp/openage/openage/util/fslike/wrapper.py", line 61, in list
    return list(self.obj.joinpath(parts).list())
  File "/var/tmp/openage/openage/util/fslike/path.py", line 90, in list
    yield from self.fsobj.list(self.parts)
  File "/var/tmp/openage/openage/util/fslike/union.py", line 108, in list
    raise FileNotFoundError(b'/'.join(parts))
FileNotFoundError: b'resources'

**Comment by goto-bus-stop** [comment]
Hmm, which version of AoE2 HD is that? the current version off steam or one of the betas?

**Comment by divinoro** [comment]
Yep, go it on some random torrent (I have somewhere AoE on the CD, but can't find it - no going to buy it again). But it has some steam_api.dll in it's root.

**Comment by goto-bus-stop** [comment]
Ahh i see. It's likely an older version of HD. I'm not sure if we should support all HD versions, since usually people who get it from Steam will have the latest version (auto-updates!), so very few people will actually be on older versions.

I'd recommend finding a version of the original Conquerors game instead for now.

**Comment by TheJJ** [comment]
So basically we'd require pre hd 4.x support for the converter, if someone wants to add the mount configuration, go for it :)
