### ISSUE TITLE
"Fontconfig could not provide font DejaVu Serif Book"

### ISSUE THREAD

**Issue by civilframe** [SFTtech/openage#525]
Hello there. I am trying to run openage on OSX 10.11.3. After following the building instructions, I ran into this error. I verified that I do have the DejaVu Serif font book installed.

```
➜  openage git:(master) make run
[  1%] Built target compilepy
[  2%] Built target cythonize
[  2%] Built target codegen
[ 84%] Built target libopenage
[ 86%] Built target openage_cppinterface_setup_checker
[ 87%] Built target openage_convert_slp
[ 88%] Built target openage_testing_misc_cpp
[ 89%] Built target openage_cabextract_lzxd
[ 90%] Built target openage_cabextract_cabchecksum
[ 91%] Built target openage_game_main_cpp
[ 92%] Built target openage_log_log_cpp
[ 93%] Built target openage_util_fslike_cpp
[ 94%] Built target openage_testing_cpp_testing
[ 96%] Built target run
[ 97%] Built target openage_cppinterface_exctranslate
[ 98%] Built target openage_cppinterface_exctranslate_tests
[ 99%] Built target openage_cppinterface_pyobject
[100%] Built target inplacemodules
[100%] Built target pxdgen
[100%] Built target distfiles
./run game
INFO [T11810063464666370627] launching engine with data directory './assets'
INFO [T11810063464666370627] SDL audio subsystems initialized
2016-03-12 12:07:57.358 run[38931:432742] 12:07:57.358 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
INFO [T11810063464666370627] Using audio device: default [freq=48000, format=32784, channels=, samples=4096]
Fontconfig error: Cannot load default config file
INFO [T11810063464666370627] Font queried: DejaVu Serif:style=Book
Traceback (most recent call last):
  File "run.py", line 15, in init run (/Users/solo/Projects/openage/run.cpp:832)
    main()
  File "/Users/solo/Projects/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/Users/solo/Projects/openage/openage/game/main.py", line 39, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 20, in openage.game.main_cpp.run_game (/Users/solo/Projects/openage/openage/game/main_cpp.cpp:858)
    result = run_game_cpp(args_cpp)
  File "", line 0, in __pyx_pw_7openage_4game_8main_cpp_1run_game(_object*, _object*, _object*)+0x3d0
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x15a
  File "", line 0, in openage::Engine::create(openage::util::Dir*, char const*)+0xfd
  File "", line 0, in openage::Engine::Engine(openage::util::Dir*, char const*)+0x433
  File "", line 0, in openage::renderer::FontManager::get_font(char const*, char const*, unsigned int)+0x1a
  File "", line 0, in openage::renderer::FontManager::get_font_filename(char const*, char const*)+0x35f
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0xf8
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0xd7
  File "libopenage/renderer/font/font_manager.cpp", line 32, in static std::string openage::renderer::FontManager::get_font_filename(const char *, const char *)
    throw Error(MSG(err) << "Fontconfig could not provide font " << family << " " << style);
openage.cppinterface.exctranslate.CPPException: Fontconfig could not provide font DejaVu Serif Book
make: *** [run] Error 1
```

Any ideas?

**Comment by TheJJ** [comment]
Hmm, i've never seen this before. Fontconfig is queried and doesn't return a font apparently.
Especially I'm confused as fontconfig should normally try to return a font that is best matching, even if the exact font isn't installed, but here it fails completely.

If you are able to program in c++ a bit, can you try playing around with `font_manager.cpp` to figure out why fontconfig misbehaves? Obviously I can't reproduce it, so you have to try your best or other mac users can try to help/assist you.

**Comment by ChipmunkV** [comment]
It's probably the "Fontconfig error: Cannot load default config file" that comes earlier.

**Comment by TheJJ** [comment]
Very well spotted. Yes, then your fontconfig setup is broken somehow. Can you reinstall it?

**Comment by civilframe** [comment]
@TheJJ I reinstalled fontconfig:

```
➜  openage git:(master) brew uninstall fontconfig
Uninstalling /usr/local/Cellar/fontconfig/2.11.1_2... (449 files, 2.9M)
➜  openage git:(master) brew install fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1_2.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/fontconfig-2.11.1_2.el_capitan.bottle.tar.gz
==> Pouring fontconfig-2.11.1_2.el_capitan.bottle.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1_2/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.11.1_2: 449 files, 2.9M
```

No change. I will try messing around with `font_manager.cpp` 😁

**Comment by civilframe** [comment]
Found the solution [here](http://stackoverflow.com/questions/35249881/octave-fontconfig-error). 

Apparently I had to add `export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig` to my bash profile to configure fontconfig. Wierd.

**Comment by TheJJ** [comment]
Phew... Do you see any possibility of fixing it on our side without a dirty workaround? Otherwise, the homebrew guys must fix it I'd say.

**Comment by civilframe** [comment]
Honestly, I'm not sure how to go about that.

**Comment by TheJJ** [comment]
Please notify me if it's an issue by us, but I really suspect homebrew or osx here.
