### ISSUE TITLE
Asset conversion fails

### ISSUE THREAD

**Issue by Jon0** [SFTtech/openage#568]
INFO [py] Game version(s) detected: Age of Empires 2: The Conquerors; Age of Empires 2: The Age of Kings; Age of Empires 2: The Conquerors, Patch 1.0c
INFO [py] converting metadata
INFO [py] [0] palette
INFO [py] [1] empires.dat
INFO [py] [2] blendomatic.dat
INFO [py] blending masks successfully exported
INFO [py] [3] player color palette
INFO [py] [4] terminal color palette
INFO [py] [5] string resources
INFO [py] [6] writing gamespec csv files
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/asdf/openage/run.cpp:832)
    main()
  File "/home/asdf/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/home/asdf/openage/openage/game/main.py", line 37, in main
    if not convert_assets(assets, args):
  File "/home/asdf/openage/openage/convert/main.py", line 143, in convert_assets
    for current_item in convert(args):
  File "/home/asdf/openage/openage/convert/driver.py", line 151, in convert
    yield from convert_metadata(args)
  File "/home/asdf/openage/openage/convert/driver.py", line 213, in convert_metadata
    data_formatter.export(args.targetdir, ("csv",))
  File "/home/asdf/openage/openage/convert/dataformat/data_formatter.py", line 188, in export
    outfile.write(content)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2122' in position 64828: ordinal not in range(256)
./run  28.62s user 0.44s system 89% cpu 32.529 total

The conversion has worked on he same assets previously.

**Comment by TheJJ** [comment]
Fixed by #569
