### ISSUE TITLE
Can't play without an Audio device -- Almost have openage working on WSL

### ISSUE THREAD

**Issue by Yanikore** [SFTtech/openage#654]
First of all thanks a ton for this project. I've been lurking this git for a while now but haven't really tried it out until now.

Because I recently switched back to Windows purely for the better graphical driver support, I also gave WSL a try. WSL is the Windows Subsystem for Linux. It's actually Microsoft's attempt at merging Ubuntu and Windows, and I must say they have been very successful so far. 

Because openage doesn't have any Windows support yet, I wanted to try it on WSL. WSL comes with Ubuntu 14.04 as of now. 14.04 doesn't have too many of the requirements for compiling openage, so I decided to upgrade to 16.04. After the update and some other tweaks and small hacks, I was able to compile openage using gcc. Everything went successful and I even was able to run the asset conversion script on my Steam HD installtion without any errors.

WSL doesn't support any hardware devices, which is why I'm stuck now. It's possible to install an X server on Windows and get multiple GUI tools working, but there isn't really a way to do this with audio. I tried to look if pulseaudio works, and it does, but openage seems to not be using it.

<details>
<summary>I'm currently stuck on the following output...</summary>
<pre>
INFO launching engine with data directory './assets' and fps limit 0
^C
INFO SDL audio subsystems initialized
^C
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "run.py", line 15, in init run (/mnt/d/Games/openage/run.cpp:1043)
    main()
  File "/mnt/d/Games/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/mnt/d/Games/openage/openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (/mnt/d/Games/openage/openage/game/main_cpp.cpp:1143)
    result = run_game_cpp(args_cpp)
  File "", line 0, in
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x239
  File "", line 0, in openage::Engine::create(openage::util::Dir*, int, bool, char const*)+0x5b
  File "", line 0, in openage::Engine::Engine(openage::util::Dir*, int, bool, char const*)+0x3d3
  File "", line 0, in openage::audio::AudioManager::AudioManager()+0x38
  File "", line 0, in openage::audio::AudioManager::AudioManager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1569
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x185
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0x9f
  File "libopenage/audio/audio_manager.cpp", line 57, in openage::audio::AudioManager::AudioManager(const string&)
    throw Error{MSG(err) << "Error opening audio device: " << SDL_GetError()};
openage.cppinterface.exctranslate.CPPException: Error opening audio device: ALSA: Couldn't open audio device: No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 47, in apport_excepthook
    try:
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "run.py", line 15, in init run (/mnt/d/Games/openage/run.cpp:1043)
    main()
  File "/mnt/d/Games/openage/openage/__main__.py", line 94, in main
    return args.entrypoint(args, cli.error)
  File "/mnt/d/Games/openage/openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (/mnt/d/Games/openage/openage/game/main_cpp.cpp:1143)
    result = run_game_cpp(args_cpp)
  File "", line 0, in
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x239
  File "", line 0, in openage::Engine::create(openage::util::Dir*, int, bool, char const*)+0x5b
  File "", line 0, in openage::Engine::Engine(openage::util::Dir*, int, bool, char const*)+0x3d3
  File "", line 0, in openage::audio::AudioManager::AudioManager()+0x38
  File "", line 0, in openage::audio::AudioManager::AudioManager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1569
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x185
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0x9f
  File "libopenage/audio/audio_manager.cpp", line 57, in openage::audio::AudioManager::AudioManager(const string&)
    throw Error{MSG(err) << "Error opening audio device: " << SDL_GetError()};
openage.cppinterface.exctranslate.CPPException: Error opening audio device: ALSA: Couldn't open audio device: No such file or directory
</pre>
</details>
<br/>

Although this is the most important afaik:

```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
openage.cppinterface.exctranslate.CPPException: Error opening audio device: ALSA: Couldn't open audio device: No such file or directory
```

I think that what I'm asking here is to make it so an audio device is not required to start the game, but I'd love to hear any sort of discussion regarding this. WSL is obviously not a priority, but it seems that this would also be present in Linux, although I can't confirm that.

Thanks again for the amazing project.

**Comment by TheJJ** [comment]
Interesting :)
It shouldn't be too hard to make the soundcard optional. If you look in `libopenage/audio/audiomanager.cpp`, you can try playing around to disable the device allocation by stubbing out features. But yes,  disabling audio the sane way is currently not possible, but we should definitely support it.

**Comment by Yanikore** [comment]
Thanks for the confirmation.

I looked at the code but it's a little above my head. Even if I could get past this error I'm sure as soon as a sound wants to play it'll crash.

Anyways, I'm glad to help and give you feedback, although I'm not of much help here.

Good luck.
