### ISSUE TITLE
Runtime error in SDL2 audio subsystems

### ISSUE THREAD

**Issue by aegistudio** [SFTtech/openage#679]
I built and ran openage but it failed to find any audio device on running game.
```
$ ./run
INFO launching engine with data directory './assets' and fps limit 0
INFO SDL audio subsystems initialized
INFO Trying to open audio device: 
Traceback (most recent call last):
  File "run.py", line 15, in init run ('openage/run.cpp:1055)
    main()
  File "openage/__main__.py", line 97, in main
    return args.entrypoint(args, cli.error)
  File "openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (openage/game/main_cpp.cpp:1155)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x270
  File "", line 0, in openage::Engine::create(openage::util::Dir*, int, bool, char const*)+0x5e
  File "", line 0, in openage::Engine::Engine(openage::util::Dir*, int, bool, char const*)+0x469
  File "", line 0, in openage::audio::AudioManager::AudioManager()+0x40
  File "", line 0, in openage::audio::AudioManager::AudioManager(std::string const&)+0x51d
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x18e
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0x7c
  File "libopenage/audio/audio_manager.cpp", line 58, in openage::audio::AudioManager::AudioManager(const string&)
    throw Error{MSG(err) << "Error opening audio device: " << SDL_GetError()};
openage.cppinterface.exctranslate.CPPException: Error opening audio device: No such audio device
```
I write a standalone program to see whether SDL2 would work on my computer, and it opened device normally in my standalone program.
I suspect there's something wrong with the `CMakeLists.txt` config in `libopenage`.

I deduced with following demo program:
```
#include "stdio.h"
#include <SDL2/SDL.h>

int main() {
        printf("%d\n", SDL_Init(SDL_INIT_AUDIO));
        printf("%d\n", SDL_GetNumAudioDevices(0));
        return 0;
}
```

When I `g++` with linker flags `/usr/local/lib/libSDL2.so -ldl -lpthread`, it returns
```
0
1
```

But when with linker flags `/usr/local/lib/libSDL2.a -ldl -lpthread`, it returns
```
0
0
```

Is it possible that linking with static one will break down audio system of SDL2?

Thanks!

**Comment by TheJJ** [comment]
Thanks for your report. That should not happen of course, but if it's really the difference between the static and dynamic library, it's not our bug. Those libraries should provide the exact same functionality.

Nevertheless, our code must be fixed so that openage can work without a soundcard (see also #654).
