### ISSUE TITLE
Invalid negative subtexture requested

### ISSUE THREAD

**Issue by Haroldoa** [SFTtech/openage#682]
I'm having trouble building this on my linux dual boot. I am not an experienced linux user.

I did the [dependency installation for ubuntu](https://github.com/SFTtech/openage/blob/master/doc/build_instructions/ubuntu_15.04.md)
Everything went fine.

I forked and then cloned the repo to `/home/USERNAME/openage`

I tried both of these in terminal in the openage directory 
"For *nix: `./configure --compiler=clang` will prepare building

You could also use `./configure --mode=release --compiler=gcc` here"

For clang I got this:
```
 _________________________________________
/ ./configure is a convenience script: it \
| creates the build directory, symlinks   |
| it, and invokes cmake for an            |
| out-of-source build.                    |
|                                         |
| Nobody is stopping you from skipping    |
| ./configure and our Makefile, and using |
| CMake directly (e.g. when packaging, or |
| using an IDE). For your convenience,    |
| ./configure even prints the direct      |
\ CMake invocation!                       /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

         build_type | Debug
       cxx_compiler | clang++
          cxx_flags | 
   exe_linker_flags | 
     install_prefix | /usr/local
module_linker_flags | 
shared_linker_flags | 

config options:

          backtrace | if_available
gperftools-profiler | if_available
gperftools-tcmalloc | False
            inotify | if_available

bindir:
/home/harold/openage/.bin/clang++-debug-Oauto-sanitize-none/

invocation:
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='' -DCMAKE_EXE_LINKER_FLAGS='' -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_LINKER_FLAGS='' -DCMAKE_SHARED_LINKER_FLAGS='' -DCXX_OPTIMIZATION_LEVEL=auto -DCXX_SANITIZE_FATAL=False -DCXX_SANITIZE_MODE=none -DWANT_BACKTRACE=if_available -DWANT_GPERFTOOLS_PROFILER=if_available -DWANT_GPERFTOOLS_TCMALLOC=False -DWANT_INOTIFY=if_available -- /home/harold/openage

(running cmake...)

 ___  ______ _______ _______ ___
|  _)/ _____|_______|_______|_  |
| | ( (____  _____      _     | |    ___  ____  _____ ____  _____  ____ _____
| |  \____ \|  ___)    | |    | |   / _ \|  _ \| ___ |  _ \(____ |/ _  | ___ |
| |_ _____) ) |        | |   _| |  | |_| | |_| | ____| | | / ___ ( (_| | ____|
|___|______/|_|        |_|  (___|   \___/|  __/|_____)_| |_\_____|\___ |_____)
                                         |_|                     (_____|

Welcome to the SFT technologies computer-aided openage build system!

You have chosen, or been chosen, to attempt the daring task of building openage.
If you have installed all the dependencies that are conveniently listed in
[doc/building.md], this _might_ just work!

If it doesn't, consider reporting the issue/asking for help in #sfttech on freenode.net.

Testing /usr/bin/python3
Testing /usr/bin/python2.7
Testing /usr/bin/python3.5dm
Testing /usr/bin/python3.5m
Testing /usr/bin/python3.5
-- Looking for suitable Python >=3.4 - Success: /usr/bin/python3
-- Checking python3 module PIL.Image - Success
-- Checking python3 module PIL.ImageDraw - Success
-- Checking python3 module numpy - Success
-- Checking python3 module pygments - Success
-- Checking utility program opusenc - Success

cpp library
	libopenage                                          [213 sources] [15 generated]
-- Could NOT find GCCBacktrace (missing:  GCCBacktrace_LIBRARY GCCBacktrace_INCLUDE_DIR) 
unavailable: backtrace
-- Could NOT find Gperftools (missing:  GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIR) 
unavailable: gperftools-profiler

cython module
	run                                                 [embedded interpreter] [noinstall]
	openage.cabextract.lzxd
	openage.cabextract.cabchecksum                      [standalone]
	openage.convert.slp
	openage.cppinterface.exctranslate
	openage.cppinterface.exctranslate_tests
	openage.cppinterface.pyobject
	openage.cppinterface.setup_checker
	openage.cvar.cvar
	openage.game.main_cpp
	openage.log.log_cpp
	openage.util.fslike.cpp
	openage.testing.cpp_testing
	openage.testing.misc_cpp

enabled options:
	inotify

disabled options:
	backtrace
	gperftools-profiler
	gperftools-tcmalloc

openage v0.3.0-547-g6592436

         compiler | Clang 3.8.0
       build type | Debug
         cxxflags |  -Wall -Wextra -pedantic -Wno-mismatched-tags -std=c++14
 build type flags | -g -O1
        build dir | /home/harold/openage/.bin/clang++-debug-Oauto-sanitize-none
   install prefix | /usr/local
py install prefix | /usr/local/lib/python3.5/dist-packages

-- Configuring done
-- Generating done
-- Build files have been written to: /home/harold/openage/.bin/clang++-debug-Oauto-sanitize-none
```

**Notice GCC Backtrace and Gperftools are missing**

**For GCC:**

```
/ ./configure is a convenience script: it \
| creates the build directory, symlinks   |
| it, and invokes cmake for an            |
| out-of-source build.                    |
|                                         |
| Nobody is stopping you from skipping    |
| ./configure and our Makefile, and using |
| CMake directly (e.g. when packaging, or |
| using an IDE). For your convenience,    |
| ./configure even prints the direct      |
\ CMake invocation!                       /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

         build_type | Release
       cxx_compiler | g++
          cxx_flags | 
   exe_linker_flags | 
     install_prefix | /usr/local
module_linker_flags | 
shared_linker_flags | 

config options:

          backtrace | if_available
gperftools-profiler | if_available
gperftools-tcmalloc | False
            inotify | if_available

bindir:
/home/harold/openage/.bin/g++-release-Oauto-sanitize-none/

invocation:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='' -DCMAKE_EXE_LINKER_FLAGS='' -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_MODULE_LINKER_FLAGS='' -DCMAKE_SHARED_LINKER_FLAGS='' -DCXX_OPTIMIZATION_LEVEL=auto -DCXX_SANITIZE_FATAL=False -DCXX_SANITIZE_MODE=none -DWANT_BACKTRACE=if_available -DWANT_GPERFTOOLS_PROFILER=if_available -DWANT_GPERFTOOLS_TCMALLOC=False -DWANT_INOTIFY=if_available -- /home/harold/openage

(running cmake...)

 ___  ______ _______ _______ ___
|  _)/ _____|_______|_______|_  |
| | ( (____  _____      _     | |    ___  ____  _____ ____  _____  ____ _____
| |  \____ \|  ___)    | |    | |   / _ \|  _ \| ___ |  _ \(____ |/ _  | ___ |
| |_ _____) ) |        | |   _| |  | |_| | |_| | ____| | | / ___ ( (_| | ____|
|___|______/|_|        |_|  (___|   \___/|  __/|_____)_| |_\_____|\___ |_____)
                                         |_|                     (_____|

Welcome to the SFT technologies computer-aided openage build system!

You have chosen, or been chosen, to attempt the daring task of building openage.
If you have installed all the dependencies that are conveniently listed in
[doc/building.md], this _might_ just work!

If it doesn't, consider reporting the issue/asking for help in #sfttech on freenode.net.

Testing /usr/bin/python3
Testing /usr/bin/python2.7
Testing /usr/bin/python3.5dm
Testing /usr/bin/python3.5m
Testing /usr/bin/python3.5
-- Looking for suitable Python >=3.4 - Success: /usr/bin/python3
-- Checking python3 module PIL.Image - Success
-- Checking python3 module PIL.ImageDraw - Success
-- Checking python3 module numpy - Success
-- Checking python3 module pygments - Success
-- Checking utility program opusenc - Success

cpp library
	libopenage                                          [213 sources] [15 generated]
-- Could NOT find GCCBacktrace (missing:  GCCBacktrace_LIBRARY GCCBacktrace_INCLUDE_DIR) 
unavailable: backtrace
-- Could NOT find Gperftools (missing:  GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIR) 
unavailable: gperftools-profiler

cython module
	run                                                 [embedded interpreter] [noinstall]
	openage.cabextract.lzxd
	openage.cabextract.cabchecksum                      [standalone]
	openage.convert.slp
	openage.cppinterface.exctranslate
	openage.cppinterface.exctranslate_tests
	openage.cppinterface.pyobject
	openage.cppinterface.setup_checker
	openage.cvar.cvar
	openage.game.main_cpp
	openage.log.log_cpp
	openage.util.fslike.cpp
	openage.testing.cpp_testing
	openage.testing.misc_cpp

enabled options:
	inotify

disabled options:
	backtrace
	gperftools-profiler
	gperftools-tcmalloc

openage v0.3.0-547-g6592436

         compiler | GNU 5.4.0
       build type | Release
         cxxflags |  -Wall -Wextra -pedantic -std=c++14 -fdiagnostics-color=auto -Wsuggest-override
 build type flags | -DNDEBUG -O3
        build dir | /home/harold/openage/.bin/g++-release-Oauto-sanitize-none
   install prefix | /usr/local
py install prefix | /usr/local/lib/python3.5/dist-packages

-- Configuring done
-- Generating done
-- Build files have been written to: /home/harold/openage/.bin/g++-release-Oauto-sanitize-none
```

**Same GCCbacktrace and gperftools are missing**

**Comment by Haroldoa** [comment]
After building with clang (only), running make, then make run I get a black screen. My window crashes after I click generate game. I am converting assets from my windows partition that has steam and Age2HD.

![Uploading Screenshot from 2016-12-26 13-21-16.png…]()

**Comment by Haroldoa** [comment]
This is my error upon clicking generate_game

`WARN Cannot enter editor mode without a game
WARN Cannot enter editor mode without a game
WARN Cannot enter editor mode without a game
INFO name1 has civilisation Gaia
INFO name2 has civilisation British
INFO gaia has civilisation French
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO Create dynamic opus loader: length=52068, channels=1
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO Create dynamic opus loader: length=131518, channels=1
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO Create dynamic opus loader: length=105884, channels=1
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
INFO DYNRES: now in use
INFO CS=19200, MX=100
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/harold/openage/run.cpp:1055)
    main()
  File "/home/harold/openage/openage/__main__.py", line 97, in main
    return args.entrypoint(args, cli.error)
  File "/home/harold/openage/openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (/home/harold/openage/openage/game/main_cpp.cpp:1155)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x334
  File "", line 0, in openage::Engine::run()+0x1f
  File "", line 0, in openage::Engine::loop()+0x527
  File "", line 0, in openage::GameRenderer::on_draw()+0x5f
  File "", line 0, in openage::Terrain::draw(openage::Engine*, openage::RenderOptions*)+0x293
  File "", line 0, in openage::Texture::draw(openage::coord::tile, unsigned int, int, openage::Texture*, int) const+0xaf
  File "", line 0, in openage::Texture::draw(int, int, unsigned int, bool, int, unsigned int, openage::Texture*, int) const+0x1ae
  File "", line 0, in openage::Texture::get_subtexture(int) const+0xf1
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x7d
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0x4d
  File "libopenage/texture.cpp", line 360, in const gamedata::subtexture *openage::Texture::get_subtexture(int) const
    throw Error(MSG(err) <<
openage.cppinterface.exctranslate.CPPException: Unknown subtexture requested for texture ./assets/missing.png: -1145602496
Makefile:22: recipe for target 'run' failed
make: *** [run] Error 1
`

**Comment by TheJJ** [comment]
Thanks for the report. Everything looks normal (it's ok that backtrace and the gperftools are missing, they're optional) except the crash when generating the game.

I wonder why the subtexture number is that far off. Can you search in your assets folder for the numbers `-1145602496`, `3149364800`, `18446744072563949120` with `ag` (the silver searcher) or `grep` please? I assume you won't find them, so we have to dig deeper why this subtexture was requested.

**Comment by Haroldoa** [comment]
Hi,

I am not sure how to search. What is the syntax to do so?

Also, do I search in /home/USERNAME/openage/assets or /home/harold/openage/bin/assets?

Thank you

**Comment by mgabris** [comment]
hi, I encountered same problem

**Comment by Monkeypac** [comment]
Hi, I have the same problem here from a basic Age2HD from a windows 7 steam.

Anyway, I just found out about the project so i'll have a look at it.

**Comment by Yanikore** [comment]
Might have something to do with the new 4.8 patch and #674

**Comment by goto-bus-stop** [comment]
Yeah, most likely due to #674. I'll have a look

**Comment by droogmic** [comment]
Has anyone found why this is happening? Fresh install, I have a very similar problem except the subtexture   requested is not negative. Ill post it heere for now until I find out if this is a different problem:

```
INFO launching engine with data directory './assets' and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=, samples=2048]
INFO Font queried: DejaVu Serif:style=Book
INFO Font file: /usr/share/fonts/TTF/DejaVuSerif.ttf
INFO Font queried: DejaVu Serif:style=Book
INFO Font file: /usr/share/fonts/TTF/DejaVuSerif.ttf
INFO Initialized SDL video subsystems.
INFO loading configuration files...
INFO [py] loading config file /home/droogmic/openage/cfg/keybinds.oac...
INFO Font queried: DejaVu Sans Mono:style=Book
INFO Font file: /usr/share/fonts/TTF/DejaVuSansMono.ttf
INFO Loading time [engine]: 0.000 s
INFO Loading time   [game]: 0.000 s
INFO Started JobManager with 4 worker threads
WARN [T5]    file ./assets/converted/terrain/15001.slp.png is not there...
WARN [T5]    file ./assets/converted/terrain/15002.slp.png is not there...
WARN [T5]    file ./assets/converted/terrain/15017.slp.png is not there...
...
WARN [T5]    file ./assets/converted/terrain/15030.slp.png is not there...
WARN [T5]    file ./assets/converted/terrain/15031.slp.png is not there...
INFO [T5] loading game specification files... will be faster once we use nyan, so please help!
WARN [T5]    No sound file found for resource_id -1, ignoring...
WARN [T5]    No sound file found for resource_id -1, ignoring...
...
WARN [T5]    No sound file found for resource_id -1, ignoring...
WARN [T5]    No sound file found for resource_id -1, ignoring...
WARN [T5]    No sound file found for resource_id 6900, ignoring...
WARN [T5]    No sound file found for resource_id 7100, ignoring...
WARN [T5]    No sound file found for resource_id 7200, ignoring...
WARN [T5]    No sound file found for resource_id 7000, ignoring...
WARN [T5]    No sound file found for resource_id 7300, ignoring...
WARN [T5]    No sound file found for resource_id 7400, ignoring...
WARN [T5]    No sound file found for resource_id 7500, ignoring...
WARN [T5]    No sound file found for resource_id 7600, ignoring...
WARN [T5]    No sound file found for resource_id 7700, ignoring...
WARN [T5]    No sound file found for resource_id 7800, ignoring...
WARN [T5]    No sound file found for resource_id 7900, ignoring...
WARN [T5]    No sound file found for resource_id 8000, ignoring...
WARN [T5]    No sound file found for resource_id 6901, ignoring...
WARN [T5]    No sound file found for resource_id 7101, ignoring...
WARN [T5]    No sound file found for resource_id 7201, ignoring...
WARN [T5]    No sound file found for resource_id 7001, ignoring...
WARN [T5]    No sound file found for resource_id 7301, ignoring...
...
WARN [T5]    No sound file found for resource_id 6448, ignoring...
WARN [T5]    No sound file found for resource_id 6449, ignoring...
WARN [T5]    No sound file found for resource_id 88113, ignoring...
WARN [T5]    No sound file found for resource_id 88114, ignoring...
WARN [T5]    No sound file found for resource_id 88119, ignoring...
...
WARN [T5]    No sound file found for resource_id 88422, ignoring...
INFO [T5] Loading time  [data]: 0.000 s
INFO gaia has civilisation Gaia
INFO name1 has civilisation British
INFO name2 has civilisation French
INFO freeing GUI...
INFO GUI was reset
INFO Stopped JobManager with 4 worker threads
INFO Cleanup gamemain
WARN Cleanup container
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/droogmic/openage/run.cpp:1055)
    main()
  File "/home/droogmic/openage/openage/__main__.py", line 97, in main
    return args.entrypoint(args, cli.error)
  File "/home/droogmic/openage/openage/game/main.py", line 47, in main
    return run_game(args, assets)
  File "openage/game/main_cpp.pyx", line 26, in openage.game.main_cpp.run_game (/home/droogmic/openage/openage/game/main_cpp.cpp:1155)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x470
  File "", line 0, in openage::Engine::run()+0x1f
  File "", line 0, in openage::Engine::loop()+0x3e1
  File "", line 0, in openage::GameRenderer::on_draw()+0x4e
  File "", line 0, in openage::Terrain::draw(openage::Engine*, openage::RenderOptions*)+0x248
  File "", line 0, in openage::Texture::draw(openage::coord::tile, unsigned int, int, openage::Texture*, int) const+0xa6
  File "", line 0, in openage::Texture::draw(int, int, unsigned int, bool, int, unsigned int, openage::Texture*, int) const+0xe9
  File "", line 0, in openage::Texture::get_subtexture(int) const+0xd7
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x16d
  File "", line 0, in openage::error::StackAnalyzer::analyze()+0x92
  File "libopenage/texture.cpp", line 358, in const gamedata::subtexture* openage::Texture::get_subtexture(int) const
    throw Error(MSG(err) <<
openage.cppinterface.exctranslate.CPPException: Unknown subtexture requested for texture ./assets/missing.png: 43721692
process 2661: arguments to dbus_connection_close() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2935.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
make: *** [Makefile:22: run] Aborted (core dumped)
```

**Comment by goto-bus-stop** [comment]
> I noticed that in my case (maybe it is simmilar here, log from running openage was not from start) openage was unable to load terrain converted assets and indeed they were not in ./assets, but "terrain looking" files were in AoE2HD folder. That may be the trigger of missing.png texture.

O, you're right. Versions 4.7 and below had the old terrain SLPs still lying around unused, but later versions don't have them anymore. When I was testing #674, i didn't clear my assets folder before, so the old converted terrains were still there :see_no_evil: Looks like we need to add conversion for HD Edition's new terrain files too

As a temporary workaround, you should still be able to convert from HD Edition if you select Patch 4.3 under Properties » Betas in HD Edition's right-click menu in Steam.

**Comment by droogmic** [comment]
Patch43 worked thanks. I don't really understand what you did in #674 so Ill let you fix that :P
It's probably worth me mentioning now as well that with an up to date AOE2HD+forgotten but no african kingdoms, my game files have do have empires2_x2_p1.dat and so the asset conversion detected African kingdoms:
```
converting from '/home/droogmic/.local/share/Steam/steamapps/common'
INFO [py] Game version(s) detected: Forgotten Empires; African Kingdoms
INFO [py] converting metadata
```

**Comment by Haroldoa** [comment]
Hello. I just tried this with a new fork and patch 43, but I am still seeing only black.

How long does it take to build after this?

WARN [T1]    No sound file found for resource_id 88426, ignoring...
WARN [T1]    No sound file found for resource_id 88420, ignoring...
WARN [T1]    No sound file found for resource_id 88421, ignoring...
WARN [T1]    No sound file found for resource_id 88422, ignoring...
INFO [T1] Loading time  [data]: 6.514 s
INFO [T2] Loading meta file: ./assets/textures/torn_paper_edge.docx
INFO [T2] Loading meta file: ./assets/converted/interface/hud0000.slp.docx
INFO [T2] Loading meta file: ./assets/converted/interface/scr5b.slp.docx

If I try to generate my game I will get an error message at this stage.

**Comment by Haroldoa** [comment]
Hi,

I just forked and cloned this today and now it works when generating the game.

I am still on patch 43 on steam. Everything to be converted fine (graphics, terrain, interface)

Very happy it loaded when I generated game too.

![movingvillager](https://cloud.githubusercontent.com/assets/23324718/22264542/3549c014-e22d-11e6-88f8-94fdf907089b.png)

**Comment by goto-bus-stop** [comment]
Good to hear! I created an issue for HD 4.8 texture support at #720. Is there anything else actionable here? Perhaps we could provide a user-friendlier error message explaining what might've gone wrong, something like

> Invalid subtexture requested. This might mean that a texture file is missing because of a bug during the media conversion.

But idk if that really helps much.

**Comment by heinezen** [comment]
This should not be a problem in the new renderer architecture anymore.
