### ISSUE TITLE
I can not compile it successfully on ubuntu 16.04, has any tip ?

### ISSUE THREAD

**Issue by Qchrlis** [SFTtech/openage#792]
Generating moc_assetmanager_link.cpp

Error compiling Cython file:
------------------------------------------------------------
...
from libopenage.util.fslike.fslike cimport FSLike

cdef extern from "/home/chrlis/workspace/test/openage/libopenage/util/path.h" namespace "openage::util" nogil:
    cppclass Path:
        ctypedef string part_t
       ^
------------------------------------------------------------

libopenage/util/path.pxd:17:8: Expected an identifier, found 'ctypedef'
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chrlis/workspace/test/openage/buildsystem/cythonize.py", line 97, in <module>
    main()
  File "/home/chrlis/workspace/test/openage/buildsystem/cythonize.py", line 74, in main
    cythonize(modules, language='c++')
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/chrlis/workspace/test/openage/openage/cvar/cvar.pyx

**Here is configure info:** 
Welcome to the SFT technologies computer-aided openage build system!

You have chosen, or been chosen, to attempt the daring task of building openage.
If you have installed all the dependencies that are conveniently listed in
[doc/building.md], this _might_ just work!

If it doesn't, consider reporting the issue/asking for help in #sfttech on freenode.net.

-- The CXX compiler identification is GNU 5.4.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test GCC_SUPPORTS_CPP14
-- Performing Test GCC_SUPPORTS_CPP14 - Success
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
usage: pythontex3.py [-h] [--version] [--encoding ENCODING]
                     [--error-exit-code {true,false}] [--runall [{true,false}]
                     | --rerun {never,modified,errors,warnings,always}]
                     [--hashdependencies [{true,false}]] [-j N] [-v]
                     [--interpreter INTERPRETER]
                     [--debug [<family>:<session>:<restart>] | --interactive
                     [<family>:<session>:<restart>]]
                     TEXNAME
pythontex3.py: error: unrecognized arguments: -c
-- Dropping invalid python interpreter '/usr/bin/pythontex3'
[21674 refs]
readline() on closed filehandle FILE at /usr/bin/python_count line 80.
readline() on closed filehandle FILE at /usr/bin/python_count line 80.
-- Dropping invalid python interpreter '/usr/bin/python_count'
-- Using python interpreter: /usr/bin/python3
-- Found Python: /usr/bin/python3 (Required is at least version "3.4") 
-- Found Cython: /usr/bin/python3 -m cython (found suitable version "0.23.4", minimum required is "0.23") 
-- Found numpy: /usr/lib/python3/dist-packages/numpy/core/include  
-- Checking python3 module PIL.Image - Success
-- Checking python3 module PIL.ImageDraw - Success
-- Checking python3 module numpy - Success
-- Checking python3 module pygments - Success
-- Checking utility program opusenc - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 

cpp library
	libopenage                                          [234 sources] [14 generated]
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/include/SDL2  
-- Found SDL2Image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so  
-- Found Opus: /usr/lib/libopusfile.so  
-- Found Epoxy: /usr/lib/x86_64-linux-gnu/libepoxy.so  
-- Found HarfBuzz: /usr/lib/x86_64-linux-gnu/libharfbuzz.so (found suitable version "1.0.1", minimum required is "1.0.0") 
-- Could NOT find GCCBacktrace (missing:  GCCBacktrace_LIBRARIES GCCBacktrace_INCLUDE_DIRS) 
unavailable: backtrace
-- Could NOT find Gperftools (missing:  GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIR) 
unavailable: gperftools-profiler
-- Found INOTIFY: /usr/include/x86_64-linux-gnu  

cython module
	run                                                 [embedded interpreter] [noinstall]
	openage.cabextract.lzxd
	openage.cabextract.cabchecksum                      [standalone]
	openage.convert.slp
	openage.convert.interface.visgrep
	openage.cppinterface.exctranslate
	openage.cppinterface.exctranslate_tests
	openage.cppinterface.pyobject
	openage.cppinterface.setup_checker
	openage.cvar.cvar
	openage.game.main_cpp
	openage.log.log_cpp
	openage.util.filelike.cpp
	openage.util.fslike.cpp
	openage.testing.cpp_testing
	openage.testing.misc_cpp

enabled options:
	inotify

disabled options:
	backtrace
	gperftools-profiler
	gperftools-tcmalloc

openage v0.3.0-859-g6952370

         compiler | GNU 5.4.1
       build type | Debug
         cxxflags |  -Wall -Wextra -pedantic -std=c++14 -fdiagnostics-color=auto -Wsuggest-override
 build type flags | -g -Og
        build dir | /home/chrlis/workspace/test/openage/build
   install prefix | /usr/local
py install prefix | /usr/local/lib/python3.5/dist-packages

-- Configuring done
-- Generating done
-- Build files have been written to: /home/chrlis/workspace/test/openage/build

**Comment by janisozaur** [comment]
You seem to have some weird python version, `pythontex3`, what's that? Can you use regular python?

**Comment by citron0xa9** [comment]
Also your cython is not up to date: `Found Cython: /usr/bin/python3 -m cython (found suitable version "0.23.4", minimum required is "0.23")`

The new minimum requirement is 0.25 as far as I knew. Try updating it by running `pip3 install cython`

**Comment by TheJJ** [comment]
Yes, the solution is to upgrade Cython. You should just upgrade to ubuntu 17.04.

The pythontex detection is a revival of #708 because the name is `pythontex3.py`, which we don't explicitly exclude yet. But as you can read, the interpreter is dropped, so the message is no problem. The Cython version is the cause for the failure.

**Comment by Qchrlis** [comment]
Thank you very much.
I have updated the version to 0.25 and compiled successfully.
