### ISSUE TITLE
Wont start when run in VirtualBox

### ISSUE THREAD

**Issue by moritzmhmk** [SFTtech/openage#847]
When I try to run it on Ubuntu in VirtualBox I get the following result:

```console
moritz@vbox-ubuntu:~/openage$ ./run
INFO [py] launching openage v0.3.0-924-g9e78dbd
INFO [py] compiled by GNU 6.2.0
INFO [py] running in DEVMODE
INFO launching engine with Path(Union(Directory(/home/moritz/openage/cfg).root @ (b'cfg',), Directory(/home/moritz/openage/assets).root @ (b'assets',)):) and fps limit 0
INFO SDL audio subsystems initialized
INFO Using audio device: default [freq=48000, format=32784, channels=2, samples=2048]
INFO Initialized SDL video subsystems.
INFO Compiled with Qt 5.6.1 and run with Qt 5.6.1
OpenGL Warning: glXQueryContext not implemented by Chromium
Traceback (most recent call last):
  File "run.py", line 15, in init run (/home/moritz/openage/run.cpp:1055)
    main()
  File "/home/moritz/openage/openage/__main__.py", line 121, in main
    return args.entrypoint(args, cli.error)
  File "/home/moritz/openage/openage/game/main.py", line 65, in main
    return run_game(args, root)
  File "openage/game/main_cpp.pyx", line 44, in openage.game.main_cpp.run_game (/home/moritz/openage/openage/game/main_cpp.cpp:1198)
    result = run_game_cpp(args_cpp)
  File "", line 0, in 
  File "", line 0, in openage::run_game(openage::main_arguments const&)+0x1b2
  File "", line 0, in openage::Engine::Engine(openage::util::Path const&, int, bool, char const*)+0x19ad
  File "", line 0, in openage::gui::GUI::GUI(SDL_Window*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, openage::gui::EngineQMLInfo*)+0x823
  File "", line 0, in openage::shader::Program::link()+0x1c
  File "", line 0, in openage::shader::Program::check(unsigned int)+0x1b4
  File "", line 0, in openage::error::Error::Error(openage::log::message const&, bool, bool)+0x174
  File "libopenage/shader/program.cpp", line 99, in void openage::shader::Program::check(GLenum)
    auto errormsg = MSG(err);
openage.cppinterface.exctranslate.CPPException: Program linking failed
ERROR: Compiled vertex shader was corrupt.
ERROR: Compiled fragment shader was corrupt.
��C:xU
```

**Comment by TheJJ** [comment]
Hm I'm not sure if we can do anything to fix this. The first interesting error message is:
```
OpenGL Warning: glXQueryContext not implemented by Chromium
```
Which seems to indicate that it somehow uses chromium with opengl? I have no idea what virtualbox does there. Anyone?

**Comment by moritzmhmk** [comment]
when I deactivate the virtualbox graphics driver (and reboot) it runs but with very poor performance (~4fps)

**Comment by Vtec234** [comment]
This looks like a bug in the graphics driver. Why on Earth does it list Chromium as the driver, do they reuse some browser code? Either way, which host are you running VirtualBox on and why are you running OpenAge in a VM rather than natively? If the game doesn't work on your host, that is the actual bug that we should solve rather than this.

**Comment by TheJJ** [comment]
https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Additions/common/crOpenGL/glx.c

**Comment by moritzmhmk** [comment]
The host is macOS (see [this](https://github.com/SFTtech/openage/issues/822#issuecomment-299736341) issue).

**Comment by ChipmunkV** [comment]
It doesn't like `identity.vert.glsl` and `maptexture.frag.glsl` shaders somehow.

**Comment by Vtec234** [comment]
Huh, apparently this has nothing to do with the browser. It's [an OpenGL implementation](http://chromium.sourceforge.net/) of the same name. There's quite a bit of unimplemented functionality in it.

**Comment by TheJJ** [comment]
I don't think we can and should do much about it. This OpenGL implementation seems to be incomplete. If you like, you can try improving our shaders, but otherwise I would just recommend not to use VirtualBox for now. Or ask them to improve their implementation.
