### ISSUE TITLE
Building failed under Debian stretch

### ISSUE THREAD

**Issue by shouhuanxiaoji** [SFTtech/openage#863]
```
[ 87%] Linking CXX shared library libopenage.so
Scanning dependencies of target cythonize
[ 87%] pxdgen: generating .pxd files from headers
[ 88%] cythonize.py: compiling .pyx files to .cpp
Please put "# distutils: language=c++" in your .pyx or .pxd file(s)
Compiling /home/xiaoji/桌面/openage-master/openage/cppinterface/setup_checker.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/cvar/cvar.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/game/main_cpp.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/log/log_cpp.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/util/filelike/cpp.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/util/fslike/cpp.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/testing/cpp_testing.pyx because it changed.
Compiling /home/xiaoji/桌面/openage-master/openage/testing/misc_cpp.pyx because it changed.
[1/8] Cythonizing /home/xiaoji/桌面/openage-master/openage/cppinterface/setup_checker.pyx
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xiaoji/桌面/openage-master/buildsystem/cythonize.py", line 97, in <module>
    main()
  File "/home/xiaoji/桌面/openage-master/buildsystem/cythonize.py", line 74, in main
    cythonize(modules, language='c++')
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 934, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1039, in cythonize_one
    result = compile([pyx_file], options)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 686, in compile
    return compile_multiple(source, options)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 664, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ModuleNode.py", line 137, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ModuleNode.py", line 389, in generate_c_code
    rootwriter.copyto(f)
  File "Cython/Compiler/Code.py", line 1583, in Cython.Compiler.Code.CCodeWriter.copyto (/build/cython-0.25.2/Cython/Compiler/Code.c:43802)
  File "/usr/lib/python3/dist-packages/Cython/StringIOTree.py", line 29, in copyto
    child.copyto(target)
  File "/usr/lib/python3/dist-packages/Cython/StringIOTree.py", line 32, in copyto
    target.write(stream_content)
  File "/usr/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/usr/lib/python3.5/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 16271-16272: ordinal not in range(256)
CMakeFiles/cythonize.dir/build.make:81: recipe for target 'py/cythonize_timefile' failed
make[3]: *** [py/cythonize_timefile] Error 1
CMakeFiles/Makefile2:118: recipe for target 'CMakeFiles/cythonize.dir/all' failed
make[2]: *** [CMakeFiles/cythonize.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:33: recipe for target 'build' failed
make: *** [build] Error 2
```

my system info is
Description:	Debian GNU/Linux 9.0 (stretch)
arch:                AMD64
gcc version:     6.3.0 20170516 (Debian 6.3.0-18)
dm:                  Cinnamon
source code:    git clone from master branch

**Comment by ChipmunkV** [comment]
Looks like cython has a problem with UTF-8.

I've also tried to make paths relative before passing to cythonize - it doesn't help (there is some different error).

    d = os.getcwd() + '/'
    return [m[len(d):] if m.startswith(d) else m for m in data]

**Comment by TheJJ** [comment]
Please try moving the openage source folder to a location where no chinese characters are in the path.

**Comment by shouhuanxiaoji** [comment]
yes，locales is zh_CN.UTF-8

**Comment by TheJJ** [comment]
After some investivation I'm quite sure it's a Cython bug. I've reported it: cython/cython#1803

**Comment by TheJJ** [comment]
I'll close this for now as this has to be handled upstream. In order to make it work, only ascii chars should be in the path, i.e. you have to either move openage out of your chinese desktop folder or rename it to english "Desktop".

Then you can "reassign" the desktop folder to be "your registered desktop folder".
The overall procedure would be:

```
mv /home/xiaoji/桌面 /home/xiaoji/Desktop
xdg-user-dirs-update --set DESKTOP /home/xiaoji/Desktop
```

Then your system is notified of the new name and all should be well.
