### ISSUE TITLE
Address sanitizer false positives.

### ISSUE THREAD

**Issue by castilma** [SFTtech/openage#884]
when compiling dea5112dbd with addresssanitizer, I get the following error. It looks like a false positive to me, but I don't know who is responsible for it.

on a side note, the thread counter is broken.
```$ ./run game
/home/mcd/.repo/ap/openage/openage/log/log_cpp.cpp:1748:59: runtime error: member call on address 0x604000023350 which does not point to an object of type 'LogSource'
0x604000023350: note: object is of type 'openage::log::NamedLogSource'
 04 00 80 52  78 f6 11 e7 6d 7f 00 00  00 00 00 00 00 00 00 00  70 33 02 00 40 60 00 00  02 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::log::NamedLogSource'
INFO [T875755398522103943] [py] launching openage v0.3.0-984-gdea5112
INFO [T875755398522103943] [py] compiled by GNU 5.4.0
INFO [T875755398522103943] [py] running in DEVMODE
INFO [T875755398522103943] launching engine with Path(Union(Directory(/home/mcd/.repo/ap/openage/cfg).root @ (b'cfg',), Directory(/home/mcd/.repo/ap/openage/assets).root @ (b'assets',)):) and fps limit 0
INFO [T875755398522103943] SDL audio subsystems initialized
INFO [T875755398522103943] Using audio device: default [freq=48000, format=32784, channels=2, samples=2048]
INFO [T875755398522103943] Initialized SDL video subsystems.
/home/mcd/.repo/ap/openage/libopenage/util/fslike/python.cpp:47:38: runtime error: member call on address 0x7fff10cf8950 which does not point to an object of type 'Path'
0x7fff10cf8950: note: object is of type 'openage::util::Path'
 6d 7f 00 00  f8 7a ea d5 6d 7f 00 00  50 5f 04 00 70 60 00 00  40 5f 04 00 70 60 00 00  30 ee 0f 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::Path'
/home/mcd/.repo/ap/openage/libopenage/util/fslike/python.cpp:46:65: runtime error: member call on address 0x7fff10cf8950 which does not point to an object of type 'Path'
0x7fff10cf8950: note: object is of type 'openage::util::Path'
 6d 7f 00 00  f8 7a ea d5 6d 7f 00 00  50 5f 04 00 70 60 00 00  40 5f 04 00 70 60 00 00  30 ee 0f 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::Path'
INFO [T875755398522103943] Compiled with Qt 5.5.1 and run with Qt 5.5.1
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6662:17: runtime error: member call on address 0x7fff10cf8090 which does not point to an object of type 'File'
0x7fff10cf8090: note: object is of type 'openage::util::File'
 6d 7f 00 00  f0 a2 11 e7 6d 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6662:17: runtime error: member call on address 0x7fff10cf7fb0 which does not point to an object of type 'File'
0x7fff10cf7fb0: note: object is of type 'openage::util::File'
 6d 7f 00 00  f0 a2 11 e7 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  70 f4 37 f8
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6667:13: runtime error: member call on address 0x7fff10cf8230 which does not point to an object of type 'File'
0x7fff10cf8230: note: object is of type 'openage::util::File'
 ff 7f 00 00  f0 a2 11 e7 6d 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  98 87 cf 10
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6574:23: runtime error: member call on address 0x7fff10cf8090 which does not point to an object of type 'File'
0x7fff10cf8090: note: object is of type 'openage::util::File'
 6d 7f 00 00  f0 a2 11 e7 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  01 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6897:13: runtime error: member call on address 0x7fff10cf8270 which does not point to an object of type 'File'
0x7fff10cf8270: note: object is of type 'openage::util::File'
 00 00 00 00  f0 a2 11 e7 6d 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  b0 82 cf 10
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6897:58: runtime error: member call on address 0x7fff10cf8230 which does not point to an object of type 'File'
0x7fff10cf8230: note: object is of type 'openage::util::File'
 ff 7f 00 00  f0 a2 11 e7 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  98 87 cf 10
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6898:11: runtime error: member call on address 0x7fff10cf8330 which does not point to an object of type 'File'
0x7fff10cf8330: note: object is of type 'openage::util::File'
 6d 7f 00 00  f0 a2 11 e7 6d 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 c9 72 67
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/openage/util/fslike/cpp.cpp:6824:23: runtime error: member call on address 0x7fff10cf8270 which does not point to an object of type 'File'
0x7fff10cf8270: note: object is of type 'openage::util::File'
 00 00 00 00  f0 a2 11 e7 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  b0 82 cf 10
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/libopenage/pyinterface/functional.h:182:54: runtime error: member call on address 0x7fff10cf8330 which does not point to an object of type 'File'
0x7fff10cf8330: note: object is of type 'openage::util::File'
 6d 7f 00 00  f0 a2 11 e7 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  00 c9 72 67
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/libopenage/gui/gui.cpp:71:22: runtime error: member call on address 0x7fff10cf8a00 which does not point to an object of type 'File'
0x7fff10cf8a00: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  88 5e 04 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/libopenage/gui/gui.cpp:79:22: runtime error: member call on address 0x7fff10cf8a00 which does not point to an object of type 'File'
0x7fff10cf8a00: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  88 5e 04 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/libopenage/gui/gui.cpp:73:67: runtime error: member call on address 0x7fff10cf8a40 which does not point to an object of type 'File'
0x7fff10cf8a40: note: object is of type 'openage::util::File'
 ff 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 ab 12 00 60 61 00 00  80 ab 12 00 60 61 00 00  60 5e 04 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
/home/mcd/.repo/ap/openage/libopenage/gui/gui.cpp:65:65: runtime error: member call on address 0x7fff10cf8a00 which does not point to an object of type 'File'
0x7fff10cf8a00: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 c6 12 00 60 61 00 00  80 c6 12 00 60 61 00 00  88 5e 04 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
INFO [T875755398522103943] loading configuration files...
INFO [T875755398522103943] [py] loading config file [Union(Directory(/home/mcd/.repo/ap/openage/cfg).root @ (b'cfg',), Directory(/home/mcd/.repo/ap/openage/assets).root @ (b'assets',))]:cfg/keybinds.oac...
/home/mcd/.repo/ap/openage/libopenage/gamedata/../util/csv.h:184:23: runtime error: member call on address 0x7fff10cf9d80 which does not point to an object of type 'File'
0x7fff10cf9d80: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 36 12 00 60 61 00 00  80 36 12 00 60 61 00 00  e0 dd 08 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
INFO [T875755398522103943] Loading time [engine]: 0.592 s
<unknown>: runtime error: member call on address 0x7fff10cf8c80 which does not point to an object of type 'File'
0x7fff10cf8c80: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 55 14 00 60 61 00 00  80 55 14 00 60 61 00 00  c0 8e 18 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8ca0 which does not point to an object of type 'File'
0x7fff10cf8ca0: note: object is of type 'openage::util::File'
 30 60 00 00  d8 7a ea d5 6d 7f 00 00  90 4f 14 00 60 61 00 00  80 4f 14 00 60 61 00 00  07 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8cc0 which does not point to an object of type 'File'
0x7fff10cf8cc0: note: object is of type 'openage::util::File'
 00 00 00 00  d8 7a ea d5 6d 7f 00 00  90 28 14 00 60 61 00 00  80 28 14 00 60 61 00 00  20 8d cf 10
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8ce0 which does not point to an object of type 'File'
0x7fff10cf8ce0: note: object is of type 'openage::util::File'
 ff 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 0d 14 00 60 61 00 00  80 0d 14 00 60 61 00 00  00 c9 72 67
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8d00 which does not point to an object of type 'File'
0x7fff10cf8d00: note: object is of type 'openage::util::File'
 e5 12 e4 ef  d8 7a ea d5 6d 7f 00 00  90 5a 15 00 60 61 00 00  80 5a 15 00 60 61 00 00  1e 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8d20 which does not point to an object of type 'File'
0x7fff10cf8d20: note: object is of type 'openage::util::File'
 00 00 00 00  d8 7a ea d5 6d 7f 00 00  90 3f 15 00 60 61 00 00  80 3f 15 00 60 61 00 00  09 3a ef f6
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8d40 which does not point to an object of type 'File'
0x7fff10cf8d40: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 ce 16 00 60 61 00 00  80 ce 16 00 60 61 00 00  19 39 ef f6
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
<unknown>: runtime error: member call on address 0x7fff10cf8d60 which does not point to an object of type 'File'
0x7fff10cf8d60: note: object is of type 'openage::util::File'
 6d 7f 00 00  d8 7a ea d5 6d 7f 00 00  90 b3 16 00 60 61 00 00  80 b3 16 00 60 61 00 00  32 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
INFO [T875755398522103943] Loading time   [game]: 0.721 s
INFO [T13377334251450678901] Loading game specification files...
/home/mcd/.repo/ap/openage/libopenage/gui/game_control_link.cpp:119:15: runtime error: load of value 190, which is not a valid value for type 'bool'
/home/mcd/.repo/ap/openage/libopenage/gamestate/../gamedata/../util/csv.h:184:23: runtime error: member call on address 0x7f6dbb3c23d0 which does not point to an object of type 'File'
0x7f6dbb3c23d0: note: object is of type 'openage::util::File'
 00 00 00 00  d8 7a ea d5 6d 7f 00 00  90 d1 2b 00 60 61 00 00  80 d1 2b 00 60 61 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'openage::util::File'
=================================================================
==21157==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x60c000592f00 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   120 bytes;
  size of the deallocated type: 1 bytes.
    #0 0x7f6df8a1c132 in operator delete(void*, unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9a132)
    #1 0x7f6de68c174d in std::default_delete<unsigned char>::operator()(unsigned char*) const /usr/include/c++/5/bits/unique_ptr.h:76
    #2 0x7f6de68c174d in std::unique_ptr<unsigned char, std::default_delete<unsigned char> >::~unique_ptr() /usr/include/c++/5/bits/unique_ptr.h:236
    #3 0x7f6de68c174d in openage::renderer::GlyphAtlas::get(openage::renderer::Font*, unsigned int) /home/mcd/.repo/ap/openage/libopenage/renderer/font/glyph_atlas.cpp:88
    #4 0x7f6de689e0d3 in openage::renderer::TextRenderer::render() /home/mcd/.repo/ap/openage/libopenage/renderer/text.cpp:159
    #5 0x7f6de623c53b in openage::Engine::loop() /home/mcd/.repo/ap/openage/libopenage/engine.cpp:456
    #6 0x7f6de623cd31 in openage::Engine::run() /home/mcd/.repo/ap/openage/libopenage/engine.cpp:311
    #7 0x7f6de62a9f15 in openage::run_game(openage::main_arguments const&) /home/mcd/.repo/ap/openage/libopenage/main.cpp:61
    #8 0x7f6de9f4b997 in __pyx_pf_7openage_4game_8main_cpp_run_game /home/mcd/.repo/ap/openage/openage/game/main_cpp.cpp:1183
    #9 0x7f6de9f4d1ca in __pyx_pw_7openage_4game_8main_cpp_1run_game /home/mcd/.repo/ap/openage/openage/game/main_cpp.cpp:1023
    #10 0x7f6df839b1b8 in PyCFunction_Call (/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0+0xa01b8)
    #11 0x7f6df84b5084 in PyEval_EvalFrameEx (/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0+0x1ba084)
    #12 0x7f6df84b5508 in PyEval_EvalFrameEx (/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0+0x1ba508)
    #13 0x4033e9 in __Pyx_PyFunction_FastCallNoKw /home/mcd/.repo/ap/openage/run.cpp:1407
    #14 0x403b2d in __Pyx_PyFunction_FastCallDict /home/mcd/.repo/ap/openage/run.cpp:1447
    #15 0x407bee in __Pyx_PyObject_CallNoArg /home/mcd/.repo/ap/openage/run.cpp:1591
    #16 0x407bee in PyInit_run /home/mcd/.repo/ap/openage/run.cpp:1055
    #17 0x408c34 in __Pyx_main /home/mcd/.repo/ap/openage/run.cpp:1800
    #18 0x408f84 in main /home/mcd/.repo/ap/openage/run.cpp:1941
    #19 0x7f6df6ec282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #20 0x402648 in _start (/home/mcd/.repo/ap/openage/run+0x402648)

0x60c000592f00 is located 0 bytes inside of 120-byte region [0x60c000592f00,0x60c000592f78)
allocated by thread T0 here:
    #0 0x7f6df8a1b6b2 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x996b2)
    #1 0x7f6de68b0bf1 in openage::renderer::Font::load_glyph(unsigned int, openage::renderer::Glyph&) const /home/mcd/.repo/ap/openage/libopenage/renderer/font/font.cpp:224
    #2 0x7f6de68c166a in openage::renderer::GlyphAtlas::get(openage::renderer::Font*, unsigned int) /home/mcd/.repo/ap/openage/libopenage/renderer/font/glyph_atlas.cpp:88
    #3 0x7f6de689e0d3 in openage::renderer::TextRenderer::render() /home/mcd/.repo/ap/openage/libopenage/renderer/text.cpp:159
    #4 0x7f6de623c53b in openage::Engine::loop() /home/mcd/.repo/ap/openage/libopenage/engine.cpp:456
    #5 0x7f6de623cd31 in openage::Engine::run() /home/mcd/.repo/ap/openage/libopenage/engine.cpp:311
    #6 0x7f6de62a9f15 in openage::run_game(openage::main_arguments const&) /home/mcd/.repo/ap/openage/libopenage/main.cpp:61
    #7 0x7f6de9f4b997 in __pyx_pf_7openage_4game_8main_cpp_run_game /home/mcd/.repo/ap/openage/openage/game/main_cpp.cpp:1183
    #8 0x7f6de9f4d1ca in __pyx_pw_7openage_4game_8main_cpp_1run_game /home/mcd/.repo/ap/openage/openage/game/main_cpp.cpp:1023
    #9 0x7f6df839b1b8 in PyCFunction_Call (/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0+0xa01b8)

SUMMARY: AddressSanitizer: new-delete-type-mismatch ??:0 operator delete(void*, unsigned long)
==21157==HINT: if you don't care about these warnings you may set ASAN_OPTIONS=new_delete_type_mismatch=0
==21157==ABORTING
```

**Comment by TheJJ** [comment]
The last error should be fixed by #889, but we still have to investigate the vptr problems.

**Comment by TheJJ** [comment]
The thread id counter issue you mention is addressed in #902.

**Comment by TheJJ** [comment]
i think this is also done by now - if not, we'll need to open new asan issues.
