### ISSUE TITLE
make pxdgen loads voltron

### ISSUE THREAD

**Issue by TheJJ** [SFTtech/openage#888]
I've got a very strange bug, pending investigation.
[`voltron`](https://github.com/snare/voltron) is a gdb plugin i use in my `.gdbinit`.
I really wonder how this ends up in the backtrace. It then imports `gdb`, which is my custom file, which crashes.

Running voltron in `pxdgen` is definitely wrong, and the backtrace indicates pygments somehow loads it?

```
make --no-print-directory -C bin pxdgen
[100%] pxdgen: generating .pxd files from headers
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jj/devel/openage/buildsystem/pxdgen.py", line 436, in <module>
    main()
  File "/home/jj/devel/openage/buildsystem/pxdgen.py", line 428, in main
    print_warnings=True
  File "/home/jj/devel/openage/buildsystem/pxdgen.py", line 352, in generate
    result = "\n".join(self.get_pxd_lines())
  File "/home/jj/devel/openage/buildsystem/pxdgen.py", line 258, in get_pxd_lines
    self.parse()
  File "/home/jj/devel/openage/buildsystem/pxdgen.py", line 215, in parse
    for token, val in self.tokenize():
  File "/home/jj/devel/openage/buildsystem/pxdgen.py", line 72, in tokenize
    lexer = get_lexer_for_filename('.cpp')
  File "/usr/lib64/python3.5/site-packages/pygments/lexers/__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/usr/lib64/python3.5/site-packages/pygments/lexers/__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/usr/lib64/python3.5/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.5/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/usr/lib64/python3.5/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/usr/lib64/python3.5/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/usr/lib64/python3.5/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/usr/lib64/python3.5/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/usr/lib64/python3.5/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/usr/lib64/python3.5/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/usr/lib64/python3.5/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib64/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "/usr/lib64/python3.5/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 14, in <module>
    import gdb
  File "/home/jj/devel/openage/gdb.py", line 4, in <module>
    class WatchBlBr(gdb.Breakpoint):
AttributeError: module 'gdb' has no attribute 'Breakpoint'

```

**Comment by TheJJ** [comment]
Further investigation revealed that `pygments` (we use it to lex c++ code) loads lexer plugins. And `voltron` installs such a one. And voltron then tries importing `gdb` because you can either load voltron within `gdb` or run a `voltron` window in some other terminal.

``` python
>>> list(iter_entry_points(LEXER_ENTRY_POINT))
[EntryPoint.parse('xonshcon = xonsh.pyghooks:XonshConsoleLexer'),
 EntryPoint.parse('xonsh = xonsh.pyghooks:XonshLexer'),
 EntryPoint.parse('lldb_att = voltron.lexers:LLDBATTLexer'),
 EntryPoint.parse('windbg_att = voltron.lexers:WinDbgATTLexer'),
 EntryPoint.parse('gdb_intel = voltron.lexers:GDBIntelLexer'),
 EntryPoint.parse('lldb_intel = voltron.lexers:LLDBIntelLexer'),
 EntryPoint.parse('vdb_att = voltron.lexers:VDBATTLexer'),
 EntryPoint.parse('windbg_intel = voltron.lexers:WinDbgIntelLexer'),
 EntryPoint.parse('gdb_att = voltron.lexers:GDBATTLexer'),
 EntryPoint.parse('vdb_intel = voltron.lexers:VDBIntelLexer'),
 EntryPoint.parse('capstone_intel = voltron.lexers:CapstoneIntelLexer')]
```

So it's really just my mistake having a `gdb.py` file lying in my openage root folder.
The working directory always takes priority over global searchpaths for python modules, so we can't blame `voltron`.

Nothing to see here, go on :stuck_out_tongue:
