### ISSUE TITLE
Asan Error on generating game

### ISSUE THREAD

**Issue by castilma** [SFTtech/openage#905]
building with asan and generating a game results in this nice message.

```
INFO [T17829216608256360205] name2 has civilisation French
/home/mcd/.repo/ap/openage/libopenage/coord/tile3.cpp:22:29: runtime error: left shift of negative value -1
/home/mcd/.repo/ap/openage/libopenage/coord/tile.cpp:23:29: runtime error: left shift of negative value -1
/home/mcd/.repo/ap/openage/libopenage/coord/tile3.cpp:23:29: runtime error: left shift of negative value -21
/home/mcd/.repo/ap/openage/libopenage/coord/tile.cpp:24:29: runtime error: left shift of negative value -21
=================================================================
==20768==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62d00062ba00 at pc 0x7feaaa319e18 bp 0x7fea88d46cb0 sp 0x7fea88d46ca0
READ of size 2 at 0x62d00062ba00 thread T3 (SDLAudioDev2)
    #0 0x7feaaa319e17 in openage::audio::SoundImpl::mix_audio(int*, int) /home/mcd/.repo/ap/openage/libopenage/audio/sound.cpp:150
    #1 0x7feaaa2bc3f7 in openage::audio::AudioManager::audio_callback(short*, int) /home/mcd/.repo/ap/openage/libopenage/audio/audio_manager.cpp:172
    #2 0x7feaaa2bc776 in operator() /home/mcd/.repo/ap/openage/libopenage/audio/audio_manager.cpp:76
    #3 0x7feaaa2bc776 in _FUN /home/mcd/.repo/ap/openage/libopenage/audio/audio_manager.cpp:77
    #4 0x7feaa689183a  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x1b83a)
    #5 0x7feaa68f109b  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x7b09b)
    #6 0x7feaa693f398  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xc9398)
    #7 0x7feabac766b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #8 0x7feabaf933dc in clone (/lib/x86_64-linux-gnu/libc.so.6+0x1073dc)

0x62d00062ba00 is located 0 bytes to the right of 38400-byte region [0x62d000622400,0x62d00062ba00)
allocated by thread T0 here:
    #0 0x7feabca056b2 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x996b2)
    #1 0x7feaaa2d9b0d in std::_MakeUniq<short []>::__array std::make_unique<short []>(unsigned long) /usr/include/c++/5/bits/unique_ptr.h:771
    #2 0x7feaaa2d9b0d in openage::audio::chunk_info_t::chunk_info_t(openage::audio::chunk_info_t::state_t, unsigned long) /home/mcd/.repo/ap/openage/libopenage/audio/dynamic_resource.cpp:19
    #3 0x7feaaa2deacc in void __gnu_cxx::new_allocator<openage::audio::chunk_info_t>::construct<openage::audio::chunk_info_t, openage::audio::chunk_info_t::state_t, unsigned long&>(openage::audio::chunk_info_t*, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/ext/new_allocator.h:120
    #4 0x7feaaa2deacc in void std::allocator_traits<std::allocator<openage::audio::chunk_info_t> >::construct<openage::audio::chunk_info_t, openage::audio::chunk_info_t::state_t, unsigned long&>(std::allocator<openage::audio::chunk_info_t>&, openage::audio::chunk_info_t*, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/alloc_traits.h:530
    #5 0x7feaaa2deacc in std::_Sp_counted_ptr_inplace<openage::audio::chunk_info_t, std::allocator<openage::audio::chunk_info_t>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<openage::audio::chunk_info_t::state_t, unsigned long&>(std::allocator<openage::audio::chunk_info_t>, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/shared_ptr_base.h:522
    #6 0x7feaaa2deacc in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<openage::audio::chunk_info_t, std::allocator<openage::audio::chunk_info_t>, openage::audio::chunk_info_t::state_t, unsigned long&>(std::_Sp_make_shared_tag, openage::audio::chunk_info_t*, std::allocator<openage::audio::chunk_info_t> const&, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/shared_ptr_base.h:617
    #7 0x7feaaa2deacc in std::__shared_ptr<openage::audio::chunk_info_t, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<openage::audio::chunk_info_t>, openage::audio::chunk_info_t::state_t, unsigned long&>(std::_Sp_make_shared_tag, std::allocator<openage::audio::chunk_info_t> const&, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/shared_ptr_base.h:1097
    #8 0x7feaaa2deacc in std::shared_ptr<openage::audio::chunk_info_t>::shared_ptr<std::allocator<openage::audio::chunk_info_t>, openage::audio::chunk_info_t::state_t, unsigned long&>(std::_Sp_make_shared_tag, std::allocator<openage::audio::chunk_info_t> const&, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/shared_ptr.h:319
    #9 0x7feaaa2deacc in std::shared_ptr<openage::audio::chunk_info_t> std::allocate_shared<openage::audio::chunk_info_t, std::allocator<openage::audio::chunk_info_t>, openage::audio::chunk_info_t::state_t, unsigned long&>(std::allocator<openage::audio::chunk_info_t> const&, openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/shared_ptr.h:620
    #10 0x7feaaa2deacc in std::shared_ptr<openage::audio::chunk_info_t> std::make_shared<openage::audio::chunk_info_t, openage::audio::chunk_info_t::state_t, unsigned long&>(openage::audio::chunk_info_t::state_t&&, unsigned long&) /usr/include/c++/5/bits/shared_ptr.h:636
    #11 0x7feaaa2deacc in openage::audio::DynamicResource::use() /home/mcd/.repo/ap/openage/libopenage/audio/dynamic_resource.cpp:51
    #12 0x7feaaa31a141 in openage::audio::Sound::play() /home/mcd/.repo/ap/openage/libopenage/audio/sound.cpp:53
    #13 0x7feaaa5838a3 in openage::Sound::play() const /home/mcd/.repo/ap/openage/libopenage/gamestate/game_spec.cpp:448
    #14 0x7feaaa9a201d in openage::ObjectProducer::place(openage::Unit*, std::shared_ptr<openage::Terrain>, openage::coord::phys3) const /home/mcd/.repo/ap/openage/libopenage/unit/producer.cpp:315
    #15 0x7feaaa9a2a9e in openage::MovableProducer::place(openage::Unit*, std::shared_ptr<openage::Terrain>, openage::coord::phys3) const /home/mcd/.repo/ap/openage/libopenage/unit/producer.cpp:397
    #16 0x7feaaa9a2f1a in openage::LivingProducer::place(openage::Unit*, std::shared_ptr<openage::Terrain>, openage::coord::phys3) const /home/mcd/.repo/ap/openage/libopenage/unit/producer.cpp:481
    #17 0x7feaaaa477fb in openage::UnitContainer::new_unit(openage::UnitType&, openage::Player&, openage::coord::phys3) /home/mcd/.repo/ap/openage/libopenage/unit/unit_container.cpp:107
    #18 0x7feaaa648abd in openage::Generator::add_units(openage::GameMain&) const /home/mcd/.repo/ap/openage/libopenage/gamestate/generator.cpp:260
    #19 0x7feaaa55ff8a in openage::GameMain::GameMain(openage::Generator const&) /home/mcd/.repo/ap/openage/libopenage/gamestate/game_main.cpp:37
    #20 0x7feaaa64fde6 in std::_MakeUniq<openage::GameMain>::__single_object std::make_unique<openage::GameMain, openage::Generator&>(openage::Generator&) /usr/include/c++/5/bits/unique_ptr.h:765
    #21 0x7feaaa64fde6 in openage::Generator::create(std::shared_ptr<openage::GameSpec>) /home/mcd/.repo/ap/openage/libopenage/gamestate/generator.cpp:314
    #22 0x7feaaa43490b in operator() /home/mcd/.repo/ap/openage/libopenage/gui/game_creator.cpp:53
    #23 0x7feaaa43490b in operator() /home/mcd/.repo/ap/openage/libopenage/gui/guisys/link/gui_item.h:187
    #24 0x7feaaa43490b in _M_invoke /usr/include/c++/5/functional:1871
    #25 0x7feaaa4b6a67 in std::function<void ()>::operator()() const /usr/include/c++/5/functional:2267
    #26 0x7feaaa4b6915 in qtsdl::GuiCallback::process(std::function<void ()> const&) /home/mcd/.repo/ap/openage/libopenage/gui/guisys/private/gui_callback.cpp:23
    #27 0x7feaaa4b2b24 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::function<void ()> const&>, void, void (qtsdl::GuiCallback::*)(std::function<void ()> const&)>::call(void (qtsdl::GuiCallback::*)(std::function<void ()> const&), qtsdl::GuiCallback*, void**) /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:501
    #28 0x7feaaa4b2b24 in void QtPrivate::FunctionPointer<void (qtsdl::GuiCallback::*)(std::function<void ()> const&)>::call<QtPrivate::List<std::function<void ()> const&>, void>(void (qtsdl::GuiCallback::*)(std::function<void ()> const&), qtsdl::GuiCallback*, void**) /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:520
    #29 0x7feaaa4b2b24 in QtPrivate::QSlotObject<void (qtsdl::GuiCallback::*)(std::function<void ()> const&), QtPrivate::List<std::function<void ()> const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:143
    #30 0x7feaa56b2bae in QMetaObject::activate(QObject*, int, int, void**) (/usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b4bae)
    #31 0x7feaaace423f in qtsdl::GameLogicCaller::in_game_logic_thread(std::function<void ()> const&) const /home/mcd/.repo/ap/openage/.bin/g++-debug-Oauto-sanitize-yes/libopenage/moc_game_logic_caller.cpp:138
    #32 0x7feaaa436927 in i<openage::gui::GameCreator::activate()::<lambda(openage::GameMainHandle*, openage::GameSpecHandle*, openage::Generator*, std::shared_ptr<openage::gui::GameCreatorSignals>)>, openage::gui::GameSpecLink*&, openage::gui::GeneratorLink*&, std::shared_ptr<openage::gui::GameCreatorSignals>&> /home/mcd/.repo/ap/openage/libopenage/gui/guisys/link/gui_item.h:185
    #33 0x7feaaa436927 in openage::gui::GameCreator::activate() /home/mcd/.repo/ap/openage/libopenage/gui/game_creator.cpp:71
    #34 0x7feaaacf4a3e in openage::gui::GameCreator::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/mcd/.repo/ap/openage/.bin/g++-debug-Oauto-sanitize-yes/libopenage/moc_game_creator.cpp:131
    #35 0x7feaaad06f34 in openage::gui::GameCreator::qt_metacall(QMetaObject::Call, int, void**) /home/mcd/.repo/ap/openage/.bin/g++-debug-Oauto-sanitize-yes/libopenage/moc_game_creator.cpp:231
    #36 0x7feaa60b3318  (/usr/lib/x86_64-linux-gnu/libQt5Qml.so.5+0x297318)

Thread T3 (SDLAudioDev2) created by T0 here:
    #0 0x7feabc9a2253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7feaa693f420  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xc9420)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/mcd/.repo/ap/openage/libopenage/audio/sound.cpp:150 openage::audio::SoundImpl::mix_audio(int*, int)
Shadow bytes around the buggy address:
  0x0c5a800bd6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a800bd700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a800bd710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a800bd720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a800bd730: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c5a800bd740:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800bd750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800bd760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800bd770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800bd780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a800bd790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==20768==ABORTING
```

**Comment by TheJJ** [comment]
obsolete with new simulation
